# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QThermonet
                                 A QGIS plugin
 This plugin links QGIS to pythermonet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-06
        copyright            : (C) 2026 by Jane Lund Andersen/VIA University College
        email                : jana@via.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Jane Lund Andersen/VIA University College'
__date__ = '2026-03-06'
__copyright__ = '(C) 2026 by Jane Lund Andersen/VIA University College'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import requests as rq
import inspect
# import matplotlib
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
# import numpy as np
from qgis.PyQt.QtGui import QIcon #, QColor
from qgis.PyQt.QtCore import QCoreApplication
# from PyQt5.QtCore import QVariant
from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingException,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFolderDestination,
    QgsVectorLayer,
    QgsWkbTypes
    )


class GetGroundConductivityAlgorithm(QgsProcessingAlgorithm):
    
    #Handle input/output
    INPUT_AREA = 'INPUT_AREA'
    DEPTH = 'DEPTH'

    def initAlgorithm(self, config=None):
        
        # 1st input
        param = QgsProcessingParameterFeatureSource(
                self.INPUT_AREA,
                "AOI (a single polygon)",
                [QgsProcessing.TypeVectorPolygon]  # Only accept polygon layers
            )
        param.setHelp(
            "The input layer must:\n"
            "- Be a polygon layer (shape or geojson format). \n"
            "- Contain a single polygon outlining the Area-Of-Interest. \n"
            "- Use a compatible CRS (preferably WGS84/EPSG:3857 or 4326)."
        )
        self.addParameter(param)

        # 2nd input (default value of 150 m)
        param = QgsProcessingParameterNumber(
                self.DEPTH,
                "Depth in meters",
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=150,
                minValue=1,
                maxValue=900
            )
        param.setHelp(
            "- Depth of averaging for the ground thermal conductivity. \n"
            "- It is defined from the ground surface with positive values downwards"
        )
        self.addParameter(param)
        
        # 3rd input (output folder)
        param = QgsProcessingParameterFolderDestination(
            'OUTPUT_FOLDER',
            'Output folder'
        )
        param.setHelp('Folder where the output PNG figures will be saved.')
        self.addParameter(param)
  

        
    def processAlgorithm(self, parameters, context, feedback):
        input_area_layer = self.parameterAsVectorLayer(parameters, self.INPUT_AREA, context)
        input_depth = self.parameterAsInt(parameters, self.DEPTH, context)
        output_folder = self.parameterAsString(parameters, 'OUTPUT_FOLDER', context)
        
        # Check input AOI layer
        feedback.pushInfo("Checking input layer ...")
        if not input_area_layer or not isinstance(input_area_layer, QgsVectorLayer):
            raise QgsProcessingException("Invalid input layer!")
        if input_area_layer.geometryType() != QgsWkbTypes.PolygonGeometry:
            raise QgsProcessingException("The input layer must be a polygon layer!")        
        features = list(input_area_layer.getFeatures()) # Check the feature count
        if len(features) != 1:
            raise QgsProcessingException("The input layer must contain exactly one polygon feature!")
        feature = features[0]         # Validate the geometry
        if not feature.isValid():
            raise QgsProcessingException("The input feature contains invalid geometry!")
        if feature.geometry().isEmpty():
            raise QgsProcessingException("The input feature has an empty geometry!")
        if not feature.geometry().isGeosValid():
            raise QgsProcessingException("The input feature geometry has errors!")

        
        # Step 1: Calculate the center coordinates of the AOI input (EPSG:25832?)
        centerX = 520000 #dummy for now
        centerY = 6200000 #dummy for now
        
        # Step 2: Create the url for the API call
        base_url = "https://data.geus.dk/geusmapmore/termiskejordarter/indexapimodel.jsp"
        #x=520000&y=6200000
        params = {
           		"x": centerX,
           		"y": centerY,
           		"crs": "EPSG:25832"
        }
        
        # Step 3: Request data from the api and check whether it was succesful
        response = rq.get(base_url, params=params)
        if response.status_code == 200:
            data = response.json()
            feedback.pushInfo(f"Ground level: {data['groundlevel']}")
            feedback.pushInfo(f"Avg thermal conductivity: {data['tc_avg_0m_150m']}")
            for aquifer in data["aquifers"]:
                feedback.pushInfo(f"Aquifer {aquifer['magasin_id']}: "
                                  f"top={aquifer['top']}m, thickness={aquifer['thickness']}m")
            for layer in data["layers"]:
                feedback.pushInfo(f"{layer['name']}: {layer['top']}m to {layer['bottom']}m")
        else:
            feedback.pushInfo(f"Request failed with status code: {response.status_code}")


       	# Step 4: Unpack the json data structure and create a figure of the local geology
       	# Check layer depths/bottoms - relative to groundlevel?
       
       	layers      = data["layers"]
       	groundlevel = data["groundlevel"]
       	phreatic = data["phreatic"]
       
       	# Define colors (random for now, later use GEUS standard colors)
       	unique_names = list({layer["name"] for layer in layers})
       	cmap         = plt.get_cmap("tab20", len(unique_names))
       	colour_map   = {name: cmap(i) for i, name in enumerate(unique_names)}
       	
       	# axis limits
       	all_tops    = [l["top"]    for l in layers]
       	all_bottoms = [l["bottom"] for l in layers]
       
       	# Initiate figure
       	fig, (ax_a, ax_b) = plt.subplots(
           	1, 2,
           	figsize       = (10, 9),
           	gridspec_kw   = {"wspace": 0.45},
       	)
       	fig.suptitle(
           	f"Geological Depth Profile  |  X={centerX}, Y={centerY}",
           	fontsize=11, fontweight="bold", y=0.98,
       	)
       
       	# Fig. 1A: Full geological profile
       	full_top    = groundlevel
       	full_bottom = min(all_bottoms)
       	margin      = (full_top - full_bottom) * 0.02   # small visual padding
       	self.draw_panel(
           	ax_a, layers, groundlevel, colour_map,
           	y_min_elev = full_bottom - margin,
           	y_max_elev = full_top    + margin,
           	title      = "Panel A – Full profile", 
             feedback   = feedback
             )
    	
       	# Fig. 1B: Zoom-in on geology down to depth that came with user input
       	panel_b_top    = groundlevel                  # surface elevation
       	panel_b_bottom = groundlevel - input_depth          # depth metres below surface
       	self.draw_panel(
           	ax_b, layers, groundlevel, colour_map,
           	y_min_elev = panel_b_bottom,
           	y_max_elev = panel_b_top,
           	title      = f"Panel B – Upper {input_depth} m below ground",
             feedback   = feedback
       	)
       
       	# legend
       	patches = [
           	mpatches.Patch(color=colour_map[name], label=name)
           	for name in sorted(unique_names)
       	]
       	fig.legend(
          	 handles   = patches,
           	title     = "Geological units",
          	 loc       = "lower center",
           	ncol      = 3,
           	fontsize  = 7,
           	title_fontsize = 8,
           	bbox_to_anchor = (0.5, 0.0),
           	framealpha = 0.8,
       	)
       	fig.subplots_adjust(bottom=0.22)   # make room for the legend
       
       	#Save figure
       	os.makedirs(output_folder, exist_ok=True)
       	out_path = os.path.join(output_folder, f"subsurface_{centerX}_{centerY}.png")
       	fig.savefig(out_path, dpi=150, bbox_inches="tight")
       	feedback.pushInfo(f"Figure saved to: {out_path}")
       
       	# Step 5: Calculate ground thermal conductivity based on json output
        if input_depth == 150:
           	tc_depthavg = data["tc_avg_0m_150m"] #Using default averaging of 150 m
        else:
            tc_depthavg = 0    	
        
        #Loop through layers
       	#Find layers with top < depth (take care wrt absolute values as above-ground is negative)
       	#If bottom < depth --> Fully within depth, weight = 1 (or actually scaling with thickness)
       	#If bottom > depth --> Calculate weight as layer thickness within depth
       	#If top < phreatic --> use tc_corrected_for_phreatic (or this should be default)
       	#Create weighted average depending on weights and depths
       	#Return this value to user (in report with profile)
       	#calculate 'sensitivity' by performing the same analysis in 10 neighbouring "cells" (e.g. 20-100 meter from center coordinates)
       	# Return value +- deviation plus a warning with method limitations
        feedback.pushInfo(f"Average thermal conductivity 0-150m: {tc_depthavg}")
        
        return {}

    # sub-functions, to be called with self. before name of function in the above
    def draw_panel(self, ax, layers, groundlevel, colour_map, y_min_elev, y_max_elev, title, feedback):
        """
        Draw geological layers as horizontal bars on `ax`.
    
        Parameters
        ----------
        y_min_elev, y_max_elev : elevation limits for the y-axis (m a.s.l.)
        """
        for layer in layers:
            top    = layer["top"]      # elevation of top    (m a.s.l.)
            bottom = layer["bottom"]   # elevation of bottom (m a.s.l.)
    
            # Skip layers entirely outside the visible window
            if top < y_min_elev or bottom > y_max_elev:
                continue
    
            # Clip to the visible window
            plot_top    = min(top,    y_max_elev)
            plot_bottom = max(bottom, y_min_elev)
    
            colour = colour_map[layer["name"]]
            ax.barh(
                y      = (plot_top + plot_bottom) / 2,   # bar centre
                width  = 1,
                height = plot_top - plot_bottom,
                color  = colour,
                edgecolor = "white",
                linewidth = 0.4,
                align  = "center",
            )
    
            # Label if the visible portion is tall enough
            if (plot_top - plot_bottom) > (y_max_elev - y_min_elev) * 0.03:
                ax.text(
                    0.5, (plot_top + plot_bottom) / 2,
                    layer["name"],
                    ha="center", va="center",
                    fontsize=7, color="black",
                    clip_on=True,
                )
    
        # Ground-level reference line
        if y_min_elev <= groundlevel <= y_max_elev:
            ax.axhline(groundlevel, color="saddlebrown", linewidth=1.2,
                       linestyle="--", label=f"Ground level ({groundlevel:.1f} m)")
            ax.legend(fontsize=7, loc="lower right")
    
        ax.set_xlim(0, 1)
        ax.set_ylim(y_min_elev, y_max_elev)
        ax.set_xticks([])
        ax.set_ylabel("Elevation (m a.s.l.)", fontsize=8)
        ax.set_title(title, fontsize=9, fontweight="bold")
        ax.yaxis.set_tick_params(labelsize=8)
        ax.invert_yaxis()   # top of profile at the top of the plot


    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Get ground conductivity'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '2. Thermonet'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def icon(self):
        cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
        icon = QIcon(os.path.join(os.path.join(cmd_folder, 'logo-thermalcond.png')))
        return icon
    
    def shortHelpString(self):
        """
        Return a short help string for the algorithm.
        """
        return (
            "<p><b> This tool: </b> <p>"
            "<p> 1.Retrieves the ground conductivity within the input AOI polygon to the selected depth "
            "The ground conductivity depends on the local geology and the water content and is found by "
	" an API call to the tool developed by GEUS (REFERENCE). <p> "
               )
    
    def createInstance(self):
        return GetGroundConductivityAlgorithm()
