# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QThermonet
                                 A QGIS plugin
 This plugin links QGIS to pythermonet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-06
        copyright            : (C) 2026 by Jane Lund Andersen/VIA University College
        email                : jana@via.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Jane Lund Andersen/VIA University College'
__date__ = '2026-03-06'
__copyright__ = '(C) 2026 by Jane Lund Andersen/VIA University College'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
from qgis import processing
import inspect
import requests as rq
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    edit,
    QgsCategorizedSymbolRenderer,
    QgsCoordinateReferenceSystem, 
    QgsCoordinateTransform, 
    QgsExpression,
    QgsExpressionContext,
    QgsExpressionContextUtils,
    QgsFeature,
    QgsField,
    QgsLineSymbol,
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingException,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterDefinition,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFileDestination,
    QgsProcessingParameterString,
    QgsProject,
    QgsRendererCategory,
    QgsSingleSymbolRenderer,
    QgsSymbol,
    QgsVectorFileWriter,
    QgsVectorLayer,
    QgsWkbTypes
    )
from PyQt5.QtCore import QVariant


class GetGroundConductivity(QgsProcessingAlgorithm):
    
    #Handle input/output
    INPUT_AREA = 'INPUT_AREA'

    def initAlgorithm(self, config=None):
        
        # 1st input
        param = QgsProcessingParameterFeatureSource(
                self.INPUT_AREA,
                "AOI (a single polygon)",
                [QgsProcessing.TypeVectorPolygon]  # Only accept polygon layers
            )
        param.setHelp(
            "The input layer must:\n"
            "- Be a polygon layer (shape or geojson format). \n"
            "- Contain a single polygon outlining the Area-Of-Interest. \n"
            "- Use a compatible CRS (preferably WGS84/EPSG:3857 or 4326)."
        )
        self.addParameter(param)
  

        
    def processAlgorithm(self, parameters, context, feedback):
        input_area_layer = self.parameterAsVectorLayer(parameters, self.INPUT_AREA, context)
        
        
        # Check input AOI layer
        feedback.pushInfo("Checking input layer ...")
        if not input_area_layer or not isinstance(input_area_layer, QgsVectorLayer):
            raise QgsProcessingException("Invalid input layer!")
        if input_area_layer.geometryType() != QgsWkbTypes.PolygonGeometry:
            raise QgsProcessingException("The input layer must be a polygon layer!")        
        features = list(input_area_layer.getFeatures()) # Check the feature count
        if len(features) != 1:
            raise QgsProcessingException("The input layer must contain exactly one polygon feature!")
        feature = features[0]         # Validate the geometry
        if not feature.isValid():
            raise QgsProcessingException("The input feature contains invalid geometry!")
        if feature.geometry().isEmpty():
            raise QgsProcessingException("The input feature has an empty geometry!")
        if not feature.geometry().isGeosValid():
            raise QgsProcessingException("The input feature geometry has errors!")

        
        # Step 1: 


    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Get ground conductivity'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '2. Thermonet'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def icon(self):
        cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
        icon = QIcon(os.path.join(os.path.join(cmd_folder, 'logo-thermalcond.png')))
        return icon
    
    def shortHelpString(self):
        """
        Return a short help string for the algorithm.
        """
        return (
            "<p><b> This tool: </b> <p>"
            "<p> 1.Retrieves the ground conductivity within the input AOI polygon to the selected depth "
            "The ground conductivity depends on the local geology and the water content and is found by "
	" an API call to the tool developed by GEUS (REFERENCE). <p> "
               )
    
    def createInstance(self):
        return GetGroundConductivityAlgorithm()
