# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QThermonet
                                 A QGIS plugin
 This plugin links QGIS to pythermonet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-10
        copyright            : (C) 2024 by Jane Lund Andersen/VIA University College
        email                : jana@via.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from __future__ import annotations

__author__ = 'Jane Lund Andersen/VIA University College'
__date__ = '2025-06-10'
__copyright__ = '(C) 2025 by Jane Lund Andersen/VIA University College'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import tempfile

from qgis.PyQt.QtGui import QIcon

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessingException,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterString,
                       QgsVectorLayer)

from .. import utils
from ..settings_editor_dialog import ROLES_BHE, ROLES_HHE, detect_mode
from ..source_placement_dialog import refresh_hhe_trench_layer, update_settings_fields

from pythermonet.components import (
    build_distribution_network,
    build_hhe_field,
    build_vhe_field,
    ground_loads_from_heat_pumps,
    localize_borefield_coordinates,
)
from pythermonet.dimensioning import (
    HHEGroundField,
    run_bhe_sizing_workflow,
    run_hhe_sizing_workflow,
    run_pipedimensioning,
)
from pythermonet.input import (
    load_settings,
    read_borefield_coordinates_tsv,
    read_heat_pumps_tsv,
    read_pipe_catalog,
    read_undimensioned_topology_tsv,
)
from pythermonet.output import print_bhe_results, print_hhe_results


def _borefield_geojson_to_dat(geojson_path: str) -> str:
    """Convert a Source Placement borefield GeoJSON to a WKT/EWKT ``.dat``.

    pythermonet's own `read_borefield_coordinates_tsv` only understands the
    WKT/EWKT TSV format, not GeoJSON. This bridges the GeoJSON layer
    QThermonet's "Source Placement" tool produces (see
    ``claude/handoffs/handoff-interactive-borefield-placement.md``) to that
    format, run fresh on every algorithm call so the ``.dat`` can never go
    stale relative to the layer -- there is no persisted ``.dat`` to
    maintain in parallel.

    Parameters
    ----------
    geojson_path : str
        Path to a borefield GeoJSON: point features with an ``id``
        attribute (matching the ``.dat``'s ``ID`` column).

    Returns
    -------
    str
        Path to a newly created temporary ``.dat`` file. Caller is
        responsible for deleting it.

    Raises
    ------
    QgsProcessingException
        If the GeoJSON can't be loaded or is missing the ``id`` field.

    """
    layer = QgsVectorLayer(geojson_path, "borefield", "ogr")
    if not layer.isValid():
        raise QgsProcessingException(f"Could not load borefield GeoJSON: {geojson_path}")

    if "id" not in [field.name() for field in layer.fields()]:
        raise QgsProcessingException(
            f"Borefield GeoJSON is missing the required 'id' field: {geojson_path}"
        )

    srid = layer.crs().authid().split(":")[-1]
    fd, dat_path = tempfile.mkstemp(suffix=".dat")
    os.close(fd)
    with open(dat_path, "w", encoding="utf-8") as dat_file:
        dat_file.write("ID\tWKT\n")
        for feature in layer.getFeatures():
            point = feature.geometry().asPoint()
            dat_file.write(
                f"{feature['id']}\tSRID={srid};POINT ({point.x()} {point.y()})\n"
            )

    return dat_path


class FullDimensioningAlgorithm(QgsProcessingAlgorithm):

    #Handle input/output
    PID = "PID"
    OUTPUT = 'OUTPUT'
    INPUT_LOAD = 'INPUT_LOAD'
    INPUT_Topology = 'INPUT_Topology'
    SETTINGS_FILE = "SETTINGS_FILE"
    BOREHOLE_COORDINATES_FILE = "BOREHOLE_COORDINATES_FILE"

    def initAlgorithm(self, config=None):
        """
        Define the parameters for the algorithm.
        """
        # Project name
        param = QgsProcessingParameterString(
                self.PID,
                "Project name"
            )
        param.setHelp(
            "Name of the project (string)\n"
        )
        self.addParameter(param)


        # Input file for specifying load for heating/cooling
        param = QgsProcessingParameterFile(
                self.INPUT_LOAD,
                self.tr("Input heat/cooling load file:"),
                extension="dat"  # Restrict selection to dat files
            )
        param.setHelp(
            "Heating and/or cooling loads for each heat pump (.dat)\n"
        )
        self.addParameter(param)


        # Input file containing topology information
        param = QgsProcessingParameterFile(
                self.INPUT_Topology,
                self.tr("Input topology file:"),
                extension="dat"  # Restrict selection to dat files
            )
        param.setHelp(
            "Topology of the thermonet with pipes and service pipes"
            " and hierarchy/level assigned (.dat)\n"
        )
        self.addParameter(param)

        # Settings file (physical/material parameters for this project)
        param = QgsProcessingParameterFile(
                self.SETTINGS_FILE,
                self.tr("Settings file:"),
                extension="json"
            )
        param.setHelp(
            "Project settings file (.json) created/edited with the "
            "'Dimensioning Settings' tool. Holds every physical/material "
            "parameter (pipes, brine, soil, sizing, ...) for this project. "
            "Its own content determines whether this run is BHE or HHE -- "
            "a project can keep both a BHE and an HHE settings file to "
            "explore both, and you pick which one to run here.\n"
        )
        self.addParameter(param)

        # Borefield layer (only used when the settings file above is BHE)
        param = QgsProcessingParameterFile(
                self.BOREHOLE_COORDINATES_FILE,
                self.tr("Borefield layer (BHE only):"),
                extension="geojson",
                optional=True
            )
        param.setHelp(
            "GeoJSON borefield layer, as produced by the 'Source Placement' "
            "tool: point features with an 'id' attribute (one flagged "
            "'is_connection_node'). Converted internally to the WKT/EWKT "
            "format pythermonet reads, fresh on every run. Required when "
            "the settings file above is a BHE settings file; ignored for "
            "HHE.\n"
        )
        self.addParameter(param)

        # Output file
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                "Output File",
                "CSV files (*.csv)",
                defaultValue=os.path.join(utils.default_save_directory(), "full_dimensioning_output.csv")
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        output_path = self.parameterAsFileOutput(parameters, self.OUTPUT, context)
        PID = self.parameterAsString(parameters, self.PID, context)

        #Handle input files
        feedback.pushInfo("Checking input files...")
        HP_file = self.parameterAsFile(parameters, self.INPUT_LOAD, context)
        if not HP_file:
            raise QgsProcessingException("Invalid heat/cooling load input file!")

        TOPO_file = self.parameterAsFile(parameters, self.INPUT_Topology, context)
        if not TOPO_file:
            raise QgsProcessingException("Invalid topology input file!")

        settings_path = self.parameterAsFile(parameters, self.SETTINGS_FILE, context)
        if not settings_path:
            raise QgsProcessingException("Invalid settings file!")

        borefield_file = self.parameterAsFile(parameters, self.BOREHOLE_COORDINATES_FILE, context)

        # Load and validate the settings file
        feedback.pushInfo("Loading settings file...")
        try:
            settings = load_settings(settings_path)
        except (FileNotFoundError, ValueError) as exc:
            raise QgsProcessingException(str(exc))

        # The settings file's own content determines BHE vs HHE -- no
        # separate mode dropdown, so a project can keep both a BHE and an
        # HHE settings file and this just picks whichever one was chosen.
        he_mode = detect_mode(settings)
        if he_mode is None:
            raise QgsProcessingException(
                "This settings file doesn't contain any role recognized as "
                "BHE- or HHE-specific, so its mode can't be determined."
            )
        feedback.pushInfo(f"Project: {PID} (detected {he_mode} mode from settings file)")

        required_roles = ROLES_BHE if he_mode == "BHE" else ROLES_HHE
        missing_roles = [role for role in required_roles if role not in settings]
        if missing_roles:
            raise QgsProcessingException(
                f"Settings file is missing the following role(s) required "
                f"for {he_mode} mode: {', '.join(missing_roles)}"
            )

        if he_mode == "BHE" and not borefield_file:
            raise QgsProcessingException(
                "A borehole coordinates file must be provided when the "
                "settings file is a BHE settings file!"
            )

        brine = settings["brine"]
        soil = settings["soil"]
        sizing = settings["sizing_parameters"]
        brine_temperature_limits = settings["brine_temperature_limits"]

        # Build the distribution network
        feedback.pushInfo("Building distribution network...")
        pipe_material_dist = settings["pipe_material_dist"]
        network_parameters = settings["distribution_network_parameters"]
        topology = read_undimensioned_topology_tsv(TOPO_file)
        distribution_network_undimensioned = build_distribution_network(
            topology,
            pipe_material=pipe_material_dist,
            network_parameters=network_parameters,
        )

        # Read heat pumps and compute ground loads
        feedback.pushInfo("Reading heat pumps and computing ground loads...")
        hp_list = read_heat_pumps_tsv(path=HP_file)
        peak_supply = settings["heat_pump_peak_supply_parameters"]
        loads = ground_loads_from_heat_pumps(hp_list, brine=brine, peak_supply=peak_supply)

        # Hydraulic (pipe) dimensioning - mode independent
        feedback.pushInfo("Dimensioning pipes...")
        pipe_catalog = read_pipe_catalog()
        hydraulic = run_pipedimensioning(
            pipe_catalog, brine, distribution_network_undimensioned, hp_list
        )

        if he_mode == "BHE":
            feedback.pushInfo("Performing BHE sizing...")
            dat_path = _borefield_geojson_to_dat(borefield_file)
            try:
                borefield_input = read_borefield_coordinates_tsv(dat_path)
            finally:
                os.remove(dat_path)
            coordinates = localize_borefield_coordinates(borefield_input)

            grout = settings["grout"]
            pipe_material_bhe = settings["pipe_material_bhe"]
            borehole = settings["borehole"]
            pipe_segment_bhe = settings["pipe_segment_bhe"]
            vhe_field_parameters = settings["vhe_field_parameters"]

            vhe_field = build_vhe_field(
                segment_parameters=pipe_segment_bhe,
                field_parameters=vhe_field_parameters,
                pipe_material=pipe_material_bhe,
                borehole=borehole,
                grout=grout,
                coordinates=coordinates,
            )

            result = run_bhe_sizing_workflow(
                ground_loads=loads,
                vhe_field=vhe_field,
                hydraulic=hydraulic,
                brine=brine,
                soil=soil,
                sizing=sizing,
                brine_temperature_limits=brine_temperature_limits,
            )
            print_bhe_results(result)
        else:
            feedback.pushInfo("Performing HHE sizing...")
            pipe_material_hhe = settings["pipe_material_hhe"]
            pipe_segment_hhe = settings["pipe_segment_hhe"]
            # `length_element` on this role is a display-only placeholder --
            # pythermonet's own HHEFieldParameters docstring says it is always
            # overwritten by the sizing solver, never a real input.
            hhe_field_parameters = settings["hhe_field_parameters"]

            pipe_infrastructure_hhe = build_hhe_field(
                segment_parameters=pipe_segment_hhe,
                field_parameters=hhe_field_parameters,
                pipe_material=pipe_material_hhe,
            )
            hhe_field = HHEGroundField(
                pipe_infrastructure=pipe_infrastructure_hhe,
                soil_thermal_conductivity_heating=float(soil.thermal_conductivity_shallow_heating),
                soil_thermal_conductivity_cooling=float(soil.thermal_conductivity_shallow_cooling),
            )

            result = run_hhe_sizing_workflow(
                ground_loads=loads,
                hhe_field=hhe_field,
                pipe_infrastructure=pipe_infrastructure_hhe,
                hydraulic=hydraulic,
                brine=brine,
                soil=soil,
                sizing=sizing,
                brine_temperature_limits=brine_temperature_limits,
            )
            print_hhe_results(result, pipe_infrastructure_hhe)

            # Write the just-computed length back into the settings file's
            # hhe_field_parameters.length_element -- unlike BHE (no length
            # field exists in vhe_field_parameters at all), this field
            # already exists and is already writable, so no pythermonet
            # schema change is needed here (see
            # claude/handoffs/2026-09-17-settings-file-results-writeback.md
            # for the full BHE/HHE asymmetry). Non-fatal: the dimensioning
            # itself already succeeded and was reported above, so a failure
            # to persist the length shouldn't fail the whole run.
            try:
                update_settings_fields(
                    settings_path,
                    {"hhe_field_parameters": {"length_element": result.sizing.length_element}},
                )
            except ValueError as exc:
                feedback.reportError(
                    f"Computed HHE length ({result.sizing.length_element:.2f} m) was not "
                    f"written back to the settings file: {exc}"
                )

            # One of the two known trigger points for refreshing an already-
            # exported HHE trench layer -- see refresh_hhe_trench_layer()'s
            # own docstring. A no-op unless the settings file has a
            # qthermonet_hhe_settings section naming a layer currently
            # loaded in the project. Runs after the write-back above so the
            # refreshed trenches reflect the newly-computed length, not the
            # placement tool's earlier guess.
            refresh_hhe_trench_layer(settings_path)

        # # Write to output file
        # feedback.pushInfo("Writing output...")
        # with open(output_path, "w", newline="") as csv_file:
        #     writer = csv.writer(csv_file)
        #     writer.writerows(table_content)

        feedback.pushInfo("Processing complete!")

        return {self.OUTPUT: output_path}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'full_dimensioning'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('Full Dimensioning')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '3. Dimensioning'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def icon(self):
        return QIcon(utils.get_logo('logo.png'))

    def shortHelpString(self):
        return ("<p> This tool performs full dimensioning of a thermonet using "
                "Pythermonet to size pipes and sources."
                "<p><b> Input: </b> <br> "
                "1. Heating/cooling load for each building/heatpump. <p>"
                "2. Pipe network topology: Topology of pipes and service pipes "
                "in thermonet circulating fluid to heatpumps/buildings. "
                "Can be created using the 'Pipe Topology' tool. <p>"
                "3. Settings file: physical/material parameters for the "
                "project, created/edited with the 'Dimensioning Settings' "
                "tool. Its own content determines whether this run is BHE "
                "or HHE -- a project can keep both a BHE and an HHE "
                "settings file to explore both. <p>"
                "4. Borefield layer (GeoJSON): required only when the "
                "settings file above is a BHE settings file. Can be "
                "created using the 'Source Placement' tool. <p>"
                "<p><b> Output:</b> Input parameters and results are stored in an output "
                "report.dat file (not yet implemented). <p>"
                "<p> <b> References: </b> <p>"
                "<p> Erbs Poulsen, S., & Tordrup, K. (2025). An integrated design "
                "model for ambient temperature district heating and cooling networks. "
                "Science and Technology for the Built Environment, 31(8), 879–888. "
                "<a href=\"https://doi.org/10.1080/23744731.2025.2523198\">https://doi.org/10.1080/23744731.2025.2523198</a>.<p>"
                "<p> Code on GitHub: <a href=\"https://github.com/BYKVAD/pythermonet\">https://github.com/BYKVAD/pythermonet</a>.<p>"
                )

    def createInstance(self):
        return FullDimensioningAlgorithm()
