# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QThermonet
                                 A QGIS plugin
 This plugin links QGIS to pythermonet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-10
        copyright            : (C) 2024 by Jane Lund Andersen/VIA University College
        email                : jana@via.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Jane Lund Andersen/VIA University College'
__date__ = '2025-06-10'
__copyright__ = '(C) 2025 by Jane Lund Andersen/VIA University College'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtGui import QIcon

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessingException,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterString)

from .. import utils
from ..settings_editor_dialog import ROLES_BHE, ROLES_HHE, detect_mode

from pythermonet.components import (
    build_distribution_network,
    build_pipe_infrastructure,
    build_vhe_field,
    ground_loads_from_heat_pumps,
    localize_borefield_coordinates,
)
from pythermonet.dimensioning import (
    HHEGroundField,
    run_bhe_sizing_workflow,
    run_hhe_sizing_workflow,
    run_pipedimensioning,
)
from pythermonet.input import (
    load_settings,
    read_borefield_coordinates_tsv,
    read_heat_pumps_tsv,
    read_pipe_catalog,
    read_undimensioned_topology_tsv,
)
from pythermonet.output import print_bhe_results, print_hhe_results


class FullDimensioningAlgorithm(QgsProcessingAlgorithm):

    #Handle input/output
    PID = "PID"
    OUTPUT = 'OUTPUT'
    INPUT_LOAD = 'INPUT_LOAD'
    INPUT_Topology = 'INPUT_Topology'
    SETTINGS_FILE = "SETTINGS_FILE"
    BOREHOLE_COORDINATES_FILE = "BOREHOLE_COORDINATES_FILE"

    def initAlgorithm(self, config=None):
        """
        Define the parameters for the algorithm.
        """
        # Project name
        param = QgsProcessingParameterString(
                self.PID,
                "Project name"
            )
        param.setHelp(
            "Name of the project (string)\n"
        )
        self.addParameter(param)


        # Input file for specifying load for heating/cooling
        param = QgsProcessingParameterFile(
                self.INPUT_LOAD,
                self.tr("Input heat/cooling load file:"),
                extension="dat"  # Restrict selection to dat files
            )
        param.setHelp(
            "Heating and/or cooling loads for each heat pump (.dat)\n"
        )
        self.addParameter(param)


        # Input file containing topology information
        param = QgsProcessingParameterFile(
                self.INPUT_Topology,
                self.tr("Input topology file:"),
                extension="dat"  # Restrict selection to dat files
            )
        param.setHelp(
            "Topology of the thermonet with pipes and service pipes"
            " and hierarchy/level assigned (.dat)\n"
        )
        self.addParameter(param)

        # Settings file (physical/material parameters for this project)
        param = QgsProcessingParameterFile(
                self.SETTINGS_FILE,
                self.tr("Settings file:"),
                extension="json"
            )
        param.setHelp(
            "Project settings file (.json) created/edited with the "
            "'Dimensioning Settings' tool. Holds every physical/material "
            "parameter (pipes, brine, soil, sizing, ...) for this project. "
            "Its own content determines whether this run is BHE or HHE -- "
            "a project can keep both a BHE and an HHE settings file to "
            "explore both, and you pick which one to run here.\n"
        )
        self.addParameter(param)

        # Borehole coordinates file (only used when the settings file above is BHE)
        param = QgsProcessingParameterFile(
                self.BOREHOLE_COORDINATES_FILE,
                self.tr("Borehole coordinates file (BHE only):"),
                extension="dat",
                optional=True
            )
        param.setHelp(
            "WKT/EWKT borehole coordinates file (ID, WKT columns; SRID= "
            "prefix required). Required when the settings file above is a "
            "BHE settings file; ignored for HHE.\n"
        )
        self.addParameter(param)

        # Output file
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                "Output File",
                "CSV files (*.csv)"
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        output_path = self.parameterAsFileOutput(parameters, self.OUTPUT, context)
        PID = self.parameterAsString(parameters, self.PID, context)

        #Handle input files
        feedback.pushInfo("Checking input files...")
        HP_file = self.parameterAsFile(parameters, self.INPUT_LOAD, context)
        if not HP_file:
            raise QgsProcessingException("Invalid heat/cooling load input file!")

        TOPO_file = self.parameterAsFile(parameters, self.INPUT_Topology, context)
        if not TOPO_file:
            raise QgsProcessingException("Invalid topology input file!")

        settings_path = self.parameterAsFile(parameters, self.SETTINGS_FILE, context)
        if not settings_path:
            raise QgsProcessingException("Invalid settings file!")

        borefield_file = self.parameterAsFile(parameters, self.BOREHOLE_COORDINATES_FILE, context)

        # Load and validate the settings file
        feedback.pushInfo("Loading settings file...")
        try:
            settings = load_settings(settings_path)
        except (FileNotFoundError, ValueError) as exc:
            raise QgsProcessingException(str(exc))

        # The settings file's own content determines BHE vs HHE -- no
        # separate mode dropdown, so a project can keep both a BHE and an
        # HHE settings file and this just picks whichever one was chosen.
        he_mode = detect_mode(settings)
        if he_mode is None:
            raise QgsProcessingException(
                "This settings file doesn't contain any role recognized as "
                "BHE- or HHE-specific, so its mode can't be determined."
            )
        feedback.pushInfo(f"Project: {PID} (detected {he_mode} mode from settings file)")

        required_roles = ROLES_BHE if he_mode == "BHE" else ROLES_HHE
        missing_roles = [role for role in required_roles if role not in settings]
        if missing_roles:
            raise QgsProcessingException(
                f"Settings file is missing the following role(s) required "
                f"for {he_mode} mode: {', '.join(missing_roles)}"
            )

        if he_mode == "BHE" and not borefield_file:
            raise QgsProcessingException(
                "A borehole coordinates file must be provided when the "
                "settings file is a BHE settings file!"
            )

        brine = settings["brine"]
        soil = settings["soil"]
        sizing = settings["sizing_parameters"]
        brine_temperature_limits = settings["brine_temperature_limits"]

        # Build the distribution network
        feedback.pushInfo("Building distribution network...")
        pipe_material_dist = settings["pipe_material_dist"]
        network_parameters = settings["distribution_network_parameters"]
        topology = read_undimensioned_topology_tsv(TOPO_file)
        distribution_network_undimensioned = build_distribution_network(
            topology,
            pipe_material=pipe_material_dist,
            network_parameters=network_parameters,
        )

        # Read heat pumps and compute ground loads
        feedback.pushInfo("Reading heat pumps and computing ground loads...")
        hp_list = read_heat_pumps_tsv(path=HP_file)
        peak_supply = settings["heat_pump_peak_supply_parameters"]
        loads = ground_loads_from_heat_pumps(hp_list, brine=brine, peak_supply=peak_supply)

        # Hydraulic (pipe) dimensioning - mode independent
        feedback.pushInfo("Dimensioning pipes...")
        pipe_catalog = read_pipe_catalog()
        hydraulic = run_pipedimensioning(
            pipe_catalog, brine, distribution_network_undimensioned, hp_list
        )

        if he_mode == "BHE":
            feedback.pushInfo("Performing BHE sizing...")
            borefield_input = read_borefield_coordinates_tsv(borefield_file)
            coordinates = localize_borefield_coordinates(borefield_input)

            grout = settings["grout"]
            pipe_material_bhe = settings["pipe_material_bhe"]
            borehole = settings["borehole"]
            pipe_segment_bhe = settings["pipe_segment_bhe"]
            vhe_field_parameters = settings["vhe_field_parameters"]

            vhe_field = build_vhe_field(
                segment_parameters=pipe_segment_bhe,
                field_parameters=vhe_field_parameters,
                pipe_material=pipe_material_bhe,
                borehole=borehole,
                grout=grout,
                coordinates=coordinates,
            )

            result = run_bhe_sizing_workflow(
                ground_loads=loads,
                vhe_field=vhe_field,
                hydraulic=hydraulic,
                brine=brine,
                soil=soil,
                sizing=sizing,
                brine_temperature_limits=brine_temperature_limits,
            )
            print_bhe_results(result)
        else:
            feedback.pushInfo("Performing HHE sizing...")
            pipe_material_hhe = settings["pipe_material_hhe"]
            pipe_segment_hhe = settings["pipe_segment_hhe"]
            pipe_infrastructure_parameters_hhe = settings["pipe_infrastructure_hhe"]

            pipe_infrastructure_hhe = build_pipe_infrastructure(
                segment_parameters=pipe_segment_hhe,
                infrastructure_parameters=pipe_infrastructure_parameters_hhe,
                pipe_material=pipe_material_hhe,
            )
            hhe_field = HHEGroundField(
                pipe_infrastructure=pipe_infrastructure_hhe,
                soil_thermal_conductivity_heating=float(soil.thermal_conductivity_shallow_heating),
                soil_thermal_conductivity_cooling=float(soil.thermal_conductivity_shallow_cooling),
            )

            result = run_hhe_sizing_workflow(
                ground_loads=loads,
                hhe_field=hhe_field,
                pipe_infrastructure=pipe_infrastructure_hhe,
                hydraulic=hydraulic,
                brine=brine,
                soil=soil,
                sizing=sizing,
                brine_temperature_limits=brine_temperature_limits,
            )
            print_hhe_results(result, pipe_infrastructure_hhe)

        # # Write to output file
        # feedback.pushInfo("Writing output...")
        # with open(output_path, "w", newline="") as csv_file:
        #     writer = csv.writer(csv_file)
        #     writer.writerows(table_content)

        feedback.pushInfo("Processing complete!")

        return {self.OUTPUT: output_path}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'full_dimensioning'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('Full Dimensioning')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '3. Dimensioning'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def icon(self):
        return QIcon(utils.get_logo('logo.png'))

    def shortHelpString(self):
        return ("<p> This tool performs full dimensioning of a thermonet using "
                "Pythermonet to size pipes and sources."
                "<p><b> Input: </b> <br> "
                "1. Heating/cooling load for each building/heatpump. <p>"
                "2. Pipe network topology: Topology of pipes and service pipes "
                "in thermonet circulating fluid to heatpumps/buildings. "
                "Can be created using the 'Pipe Topology' tool. <p>"
                "3. Settings file: physical/material parameters for the "
                "project, created/edited with the 'Dimensioning Settings' "
                "tool. Its own content determines whether this run is BHE "
                "or HHE -- a project can keep both a BHE and an HHE "
                "settings file to explore both. <p>"
                "4. Borehole coordinates file: required only when the "
                "settings file above is a BHE settings file. <p>"
                "<p><b> Output:</b> Input parameters and results are stored in an output "
                "report.dat file (not yet implemented). <p>"
                "<p> <b> References: </b> <p>"
                "<p> Erbs Poulsen, S., & Tordrup, K. (2025). An integrated design "
                "model for ambient temperature district heating and cooling networks. "
                "Science and Technology for the Built Environment, 31(8), 879–888. "
                "<a href=\"https://doi.org/10.1080/23744731.2025.2523198\">https://doi.org/10.1080/23744731.2025.2523198</a>.<p>"
                "<p> Code on GitHub: <a href=\"https://github.com/BYKVAD/pythermonet\">https://github.com/BYKVAD/pythermonet</a>.<p>"
                )

    def createInstance(self):
        return FullDimensioningAlgorithm()
