# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QThermonet
                                 A QGIS plugin
 This plugin links QGIS to pythermonet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-06
        copyright            : (C) 2026 by Jane Lund Andersen/VIA University College
        email                : jana@via.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Jane Lund Andersen/VIA University College'
__date__ = '2026-03-06'
__copyright__ = '(C) 2026 by Jane Lund Andersen/VIA University College'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import requests as rq
import inspect
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingException,
    QgsProcessingParameterNumber,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFolderDestination
    )
from ..utils import calculate_tc, fetch_api_data, get_representative_point


class GetGroundConductivityAlgorithm(QgsProcessingAlgorithm):
    
    #Handle input/output
    INPUT_AREA = 'INPUT_AREA'
    DEPTH = 'DEPTH'

    def initAlgorithm(self, config=None):
        
        # 1st input
        param = QgsProcessingParameterFeatureSource(
                self.INPUT_AREA,
                "AOI (a single polygon, line, or point)",
                [QgsProcessing.TypeVectorPolygon,
                 QgsProcessing.TypeVectorLine,
                 QgsProcessing.TypeVectorPoint]  # Only accept polygon, polyline, or point layers
            )
        param.setHelp(
            "The input layer must:\n"
            "- Be a polygon, line, or point layer (shape or geojson format). \n"
            "- Contain a single feature with the Area-Of-Interest. \n"
            "- Use a compatible CRS (preferably WGS84/EPSG:3857 or 4326)."
        )
        self.addParameter(param)

        # 2nd input (default value of 150 m)
        param = QgsProcessingParameterNumber(
                self.DEPTH,
                "Depth in meters",
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=150,
                minValue=1,
                maxValue=900
            )
        param.setHelp(
            "- Depth of averaging for the ground thermal conductivity. \n"
            "- It is defined from the ground surface with positive values downwards"
        )
        self.addParameter(param)
        
        # 3rd input (output folder)
        param = QgsProcessingParameterFolderDestination(
            'OUTPUT_FOLDER',
            'Output folder'
        )
        param.setHelp('Folder where the output PNG figures will be saved.')
        self.addParameter(param)
  

        
    def processAlgorithm(self, parameters, context, feedback):
        input_area_layer = self.parameterAsVectorLayer(parameters, self.INPUT_AREA, context)
        input_depth = self.parameterAsInt(parameters, self.DEPTH, context)
        output_folder = self.parameterAsString(parameters, 'OUTPUT_FOLDER', context)

        # Step 1: Calculate the center coordinates of the AOI input (EPSG:25832)
        feedback.pushInfo("Calculating input coordinates...")
        centerX, centerY = get_representative_point(input_area_layer)
        feedback.pushInfo(f"Coordinates (EPSG:25832): X={centerX}, Y={centerY}")
        
        # #Hardcode for temporary check
        # centerX = 520000
        # centerY = 6200000
        # feedback.pushInfo(f"Temporary overwriting with hard-coded coordinates (EPSG:25832): X={centerX}, Y={centerY}")
        
        
        # Step 2: Request data from the api and check whether it was succesful
        feedback.pushInfo(f"Requesting data for X={centerX}, Y={centerY}")
        try:
            data = fetch_api_data(centerX, centerY)
        except ValueError as e:
            raise QgsProcessingException(str(e))
            
        # feedback.pushInfo(f"Raw API response: {data}")
        feedback.pushInfo(f"Ground level: {data['groundlevel']} m a.s.l.")
        feedback.pushInfo(f"Water table: {data['groundlevel']-data['phreatic']} m a.s.l.")
        feedback.pushInfo(f"Avg thermal conductivity to 150 m: {data['tc_avg_0m_150m']}")
        for aquifer in data["aquifers"]:
            feedback.pushInfo(f"Aquifer {aquifer['magasin_id']}: "
                              f"top={aquifer['top']}m, thickness={aquifer['thickness']}m")
        for layer in data["layers"]:
            feedback.pushInfo(f"{layer['name']}: {layer['top']}m.b.g. to {layer['bottom']}m.b.g.")


       	# Step 3: Unpack the json data structure and create a figure of the local geology
       	layers      = data["layers"]
       	groundlevel = data["groundlevel"]
       	phreatic    = data["phreatic"]
       
       	# Define colors (random for now, later use GEUS standard colors)
       	unique_names = list({layer["name"] for layer in layers})
       	cmap         = plt.get_cmap("tab20", len(unique_names))
       	colour_map   = {name: cmap(i) for i, name in enumerate(unique_names)}
       
       	# Initiate figure
       	# fig, (ax_a, ax_b) = plt.subplots(
        #    	1, 2,
        #    	figsize       = (10, 11),
        #    	gridspec_kw   = {"wspace": 0.45},
       	# )
        fig = plt.figure(figsize=(13, 11))
        gs  = GridSpec(
            1, 5,
            figure       = fig,
            width_ratios = [4, 1, 0.8, 4, 1],   # geology, tc, geology, tc
            wspace       = 0.08,            # tight spacing between geology and tc panels
            left         = 0.08,
            right        = 0.95,
        )
        
        ax_a    = fig.add_subplot(gs[0, 0])
        ax_a_tc = fig.add_subplot(gs[0, 1])
        ax_b    = fig.add_subplot(gs[0, 3])
        ax_b_tc = fig.add_subplot(gs[0, 4])
        
       	fig.suptitle(
           	f"Geological Depth Profile  |  X={centerX}, Y={centerY}",
           	fontsize=11, fontweight="bold", y=0.98,
       	)
       
        
       	# Fig. 1A: Full geological profile (upper 1 km)
       	panel_a_top    = groundlevel
        panel_a_bottom = groundlevel - 1000 # max(l["bottom"] for l in layers)
       	self.draw_panel(
           	ax_a, layers, groundlevel, phreatic, colour_map,
           	y_min_elev = panel_a_top,
           	y_max_elev = panel_a_bottom,
           	title      = "Panel A – Upper 1 km", 
             feedback   = feedback
             )
        self.draw_tc_panel(ax_a_tc, layers, groundlevel, panel_a_top, panel_a_bottom) #feedback
    	
       	# Fig. 1B: Zoom-in on geology down to depth that came with user input
       	panel_b_top    = groundlevel
        panel_b_bottom = groundlevel - input_depth      # depth metres below surface
       	self.draw_panel(
           	ax_b, layers, groundlevel, phreatic, colour_map,
           	y_min_elev = panel_b_top,
           	y_max_elev = panel_b_bottom,
           	title      = f"Panel B – Upper {input_depth} m",
             feedback   = feedback
       	)
        self.draw_tc_panel(ax_b_tc, layers, groundlevel, panel_b_top, panel_b_bottom) #feedback
       
       	# legend
       	# Sort unique names by their top value (shallowest first)
        sorted_names = sorted(unique_names, key=lambda name: next(l["top"] for l in layers if l["name"] == name))
        
        patches = [
            mpatches.Patch(color=colour_map[name], label=name)
            for name in sorted_names
        ]
                     
       
       	# Step 4: Calculate ground thermal conductivity based on json output and check spatial sensitivity          
        offset     = 500  # metres
        offsets    = [
            ( 0,       0),       # center
            ( offset,  0),       # E
            (-offset,  0),       # W
            ( 0,       offset),  # N
            ( 0,      -offset),  # S
            ( offset,  offset),  # NE
            (-offset,  offset),  # NW
            ( offset, -offset),  # SE
            (-offset, -offset),  # SW
        ]
        
        tc_values = []
        for dx, dy in offsets:
            x  = centerX + dx
            y  = centerY + dy
            tc = calculate_tc(x, y, input_depth) #function located in utils.py
            # tc = self.calculate_tc_internal(x, y, input_depth, feedback) #function located below
            if tc is not None:
                tc_values.append(tc)
                feedback.pushInfo(f"  TC at ({x}, {y}): {tc:.2f} W/m·K")
            else:
                feedback.pushInfo("Warning: could not retrieve ground thermal conductivity")
        
        # Center point value is the primary result
        tc_depthavg = tc_values[0] if tc_values else None
        
        # Spatial uncertainty estimate from spread across all 9 points
        if len(tc_values) > 1:
            tc_min   = min(tc_values)
            tc_max   = max(tc_values)
            tc_range = tc_max - tc_min
            tc_dev = (tc_range/2)/tc_depthavg*100
            feedback.pushInfo(f"Average thermal conductivity 0-{input_depth} m: {tc_depthavg:.2f} W/m·K")
            feedback.pushInfo(f"Sensitivity estimate — min: {tc_min:.2f}, max: {tc_max:.2f}, range: {tc_range:.2f} W/m·K ({tc_dev:.1f} %)")
        else:
            feedback.pushInfo("Warning: insufficient points to estimate uncertainty")
            
        # Depth sensitivity: +/- 25% of input_depth at center point only
        dev=25
        depth_low  = round(input_depth * (1-dev/100))
        depth_high = round(input_depth * (1+dev/100))
        
        tc_depth_low  = calculate_tc(centerX, centerY, depth_low)
        tc_depth_high = calculate_tc(centerX, centerY, depth_high)
        
        if tc_depth_low is not None and tc_depth_high is not None:
            tc_hdev = ((tc_depth_high - tc_depthavg)/tc_depthavg)*100
            tc_ldev = ((tc_depth_low - tc_depthavg)/tc_depthavg)*100
            feedback.pushInfo(f"Depth sensitivity (+- {dev:.0f}%): Depth={depth_low}m: {tc_depth_low:.2f} W/m·K ({tc_ldev:.1f}%); Depth={depth_high}m: {tc_depth_high:.2f} W/m·K  ({tc_hdev:.1f}%)")
        else:
            feedback.pushInfo("Warning: could not retrieve TC values for depth sensitivity")


        # Step 5: Add information to figure before saving
        # Build figure annotation text - spatial and depth sensitivity reported separately
        if len(tc_values) > 1:
            geo_text = (
                f"Ground thermal conductivity (0–{input_depth} m): {tc_depthavg:.2f} W/m·K\n"
                f"Spatial sensitivity ({offset} m radius): min={tc_min:.2f}, max={tc_max:.2f}, range={tc_range:.2f} W/m·K ({tc_dev:.1f} %)"
            )
        else:
            geo_text = (
                f"Ground thermal conductivity (0–{input_depth} m): {tc_depthavg:.2f} W/m·K"
            )
        
        if tc_depth_low is not None and tc_depth_high is not None:
            depth_text = (
                f"Depth sensitivity (+- {dev:.0f}%): Depth={depth_low}m: {tc_depth_low:.2f} W/m·K ({tc_ldev:.1f}%); Depth={depth_high}m: {tc_depth_high:.2f} W/m·K  ({tc_hdev:.1f}%)"
            )
        else:
            depth_text = "Depth sensitivity: could not be estimated"
        
        tc_text = geo_text + "\n" + depth_text
        
        # Add text box just above the legend
        fig.text(
            0.5, 0.21,                    # x, y in figure coordinates (just above legend)
            tc_text,
            ha        = "center",
            va        = "bottom",
            fontsize  = 10,
            family    = "monospace",      # monospace keeps the columns aligned
            bbox      = dict(
                boxstyle    = "round,pad=0.4",
                facecolor   = "lightgray",
                edgecolor   = "gray",
                linewidth   = 0.8,
                alpha       = 0.9
            )
        )
        
        # Adjust legend position to sit below the text box
        fig.legend(
            handles        = patches,
            title          = "Geological units",
            loc            = "lower center",
            ncol           = 4,
            fontsize       = 7,
            title_fontsize = 8,
            bbox_to_anchor = (0.5, 0.0),
            framealpha     = 0.8,
        )
        fig.subplots_adjust(bottom=0.28)  # increase bottom margin to fit both text box and legend
        
        
       	#Save figure
       	os.makedirs(output_folder, exist_ok=True)
       	out_path = os.path.join(output_folder, f"subsurface_{centerX}_{centerY}_{input_depth}m.png")
       	fig.savefig(out_path, dpi=150, bbox_inches="tight")
       	feedback.pushInfo(f"Figure saved to: {out_path}")
       
        return {}


    # sub-functions, to be called with self. before name of function in the above

    def draw_panel(self, ax, layers, groundlevel, phreatic, colour_map, y_min_elev, y_max_elev, title, feedback=None):

        for layer in layers:
            # Convert depth below surface to elevation (m a.s.l.)
            top    = groundlevel - layer["top"]
            bottom = groundlevel - layer["bottom"]
    
            # Skip layers entirely outside the visible window
            if top < y_max_elev or bottom > y_min_elev:
                continue
    
            # Clip to visible window
            plot_top    = min(top,    y_min_elev)
            plot_bottom = max(bottom, y_max_elev)
    
            colour = colour_map[layer["name"]]
            ax.barh(
                y         = (plot_top + plot_bottom) / 2,
                width     = 1,
                height    = plot_top - plot_bottom,
                color     = colour,
                edgecolor = "white",
                linewidth = 0.4,
                align     = "center",
            )
    
            if (plot_top - plot_bottom) > (y_min_elev - y_max_elev) * 0.03:
                ax.text(
                    0.5, (plot_top + plot_bottom) / 2,
                    f"{layer["name"]}: tc =  {layer["tc_corrected_for_phreatic"]:.2f}  W/m·K",
                    ha="center", va="center",
                    fontsize=7, color="black",
                    clip_on=True,
                )
    
        # Groundwater table line at elevation: groundlevel - phreatic
        gw_elevation = groundlevel - phreatic
        ax.axhline(gw_elevation, color="steelblue", linewidth=1.2,
                   linestyle="--", label=f"Groundwater table ({gw_elevation:.1f} m a.s.l.)")
        ax.legend(fontsize=7, loc="lower right")
    
        ax.set_xlim(0, 1)
        ax.set_ylim(y_min_elev, y_max_elev)
        ax.invert_yaxis()
        ax.set_xticks([])
        ax.set_ylabel("Elevation (m a.s.l.)", fontsize=8)
        ax.set_title(title, fontsize=9, fontweight="bold")
        ax.yaxis.set_tick_params(labelsize=8)
        
    def draw_tc_panel(self, ax, layers, groundlevel, y_min_elev, y_max_elev, feedback=None):
    
        sorted_layers = sorted(layers, key=lambda l: l["top"])
    
        for i, layer in enumerate(sorted_layers):
            top    = groundlevel - layer["top"]
            bottom = groundlevel - layer["bottom"]
            tc     = layer["tc_corrected_for_phreatic"]
    
            # Skip layers entirely outside the visible window
            if top < y_max_elev or bottom > y_min_elev:
                if feedback:
                    feedback.pushInfo(f"  TC SKIPPED: {layer['name']} top={top:.2f}, bottom={bottom:.2f}")
                continue
    
            # Clip to visible window
            plot_top    = min(top,    y_min_elev)
            plot_bottom = max(bottom, y_max_elev)
    
            if feedback:
                feedback.pushInfo(f"  TC PLOTTING: {layer['name']} plot_top={plot_top:.2f}, plot_bottom={plot_bottom:.2f}, tc={tc}")
    
            # Horizontal line at tc value spanning the layer
            ax.plot(
                [tc, tc],
                [plot_top, plot_bottom],
                color     = "black",
                linewidth = 1.2,
            )
            
            # Fill area to the left of the curve
            ax.fill_betweenx(
                y      = [plot_top, plot_bottom],
                x1     = 0.8,              # left edge of plot (matches ax.set_xlim left value)
                x2     = tc,
                color  = "mediumpurple",
                alpha  = 0.25,
            )
    
            # Vertical connector to next layer
            if i < len(sorted_layers) - 1:
                next_layer  = sorted_layers[i + 1]
                tc_next     = next_layer["tc_corrected_for_phreatic"]
                join_elev   = groundlevel - layer["bottom"]
                join_clipped = max(join_elev, y_max_elev)
                ax.plot(
                    [tc, tc_next],
                    [join_clipped, join_clipped],
                    color     = "black",
                    linewidth = 0.6,
                )
    
        ax.set_ylim(y_min_elev, y_max_elev)
        ax.invert_yaxis()
        ax.set_yticklabels([])
        ax.yaxis.set_tick_params(length=0)
        ax.set_xlabel("TC\n(W/m·K)", fontsize=6)
        ax.xaxis.set_label_position("top")
        ax.xaxis.tick_top()
        ax.tick_params(axis="x", labelsize=6)
        ax.set_xlim(0.8, 3.0)
        ax.grid(axis="x", linewidth=0.3, linestyle=":", color="gray")
        for spine in ax.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(0.6)
        
    def calculate_tc_internal(self, centerX, centerY, input_depth, feedback=None):
        """Fetch API data and calculate weighted average thermal conductivity for a single point."""
        
        base_url = "https://data.geus.dk/geusmapmore/termiskejordarter/indexapimodel.jsp"
        params   = {"x": centerX, "y": centerY}
        
        response = rq.get(base_url, params=params)
        
        if response.status_code != 200:
            if feedback:
                feedback.pushInfo(f"  Request failed for X={centerX}, Y={centerY}: status {response.status_code}")
            return None
        
        data = response.json()
        
        if "error" in data:
            if feedback:
                feedback.pushInfo(f"  API error for X={centerX}, Y={centerY}: {data['error']}")
            return None
        
        if input_depth == 150:
            return data["tc_avg_0m_150m"]
        
        layers = data["layers"]
        
        tc_weighted_sum = 0
        total_thickness = 0
    
        for layer in layers:
            layer_top    = layer["top"]
            layer_bottom = layer["bottom"]
    
            if layer_bottom <= 0 or layer_top >= input_depth:
                continue
    
            clipped_top    = max(layer_top,    0)
            clipped_bottom = min(layer_bottom, input_depth)
    
            thickness_within_depth = clipped_bottom - clipped_top
    
            if thickness_within_depth > 0:
                tc_weighted_sum += layer["tc_corrected_for_phreatic"] * thickness_within_depth
                total_thickness += thickness_within_depth
    
        if total_thickness > 0:
            return tc_weighted_sum / total_thickness
        else:
            return None

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Get ground conductivity'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '2. Thermonet'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def icon(self):
        return QIcon(utils.get_logo('logo-thermalcond.png'))
    
    def shortHelpString(self):
        """
        Return a short help string for the algorithm.
        """
        return (
            "<p><b> This tool: </b> <p>"
            "<p> 1.Calculates the ground thermal conductivity at the input AOI: polygon"
            " centroid, line center, or point - averaged to the input depth. <p> "
            "<p> 2. Creates a report of the ground thermal conductivity based on"
            " the local geology and water content, and provides spatial and depth sensitivity "
            "estimates. The report is saved to the selected folder (png). "
            "<p> Data on ground water table and local geology is"
            " retrieved by an API call to the tool developed by GEUS (REFERENCE). <p> "
               )
    
    def createInstance(self):
        return GetGroundConductivityAlgorithm()
