# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QThermonet
                                 A QGIS plugin
 This plugin links QGIS to pythermonet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-10
        copyright            : (C) 2025 by Jane Lund Andersen/VIA University College
        email                : jana@via.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Jane Lund Andersen/VIA University College'
__date__ = '2025-06-10'
__copyright__ = '(C) 2025 by Jane Lund Andersen/VIA University College'
__revision__ = '$Format:%H$'

# This will get replaced with a git SHA1 when you do a git archive

import os
from qgis import processing
import inspect
from urllib.parse import quote
from osgeo import gdal

import requests as rq
from .. import utils
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtCore import QCoreApplication, QMetaType
from qgis.core import (
    edit,
    QgsCategorizedSymbolRenderer,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsExpression,
    QgsExpressionContext,
    QgsExpressionContextUtils,
    QgsFeature,
    QgsField,
    QgsLineSymbol,
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingException,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterDefinition,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFileDestination,
    QgsProject,
    QgsRendererCategory,
    QgsSingleSymbolRenderer,
    QgsSymbol,
    QgsVectorFileWriter,
    QgsVectorLayer,
    QgsWkbTypes
    )


class GetBuildingsAndBBRAlgorithm(QgsProcessingAlgorithm):

    #Handle input/output
    INPUT_AREA = 'INPUT_AREA'
    OUTPUT_BUILD = 'OUTPUT_BUILD'
    OUTPUT_ROADS = 'OUTPUT_ROADS'

    def initAlgorithm(self, config=None):
        
        # 1st input
        param = QgsProcessingParameterFeatureSource(
                self.INPUT_AREA,
                "AOI (a single polygon)",
                [QgsProcessing.TypeVectorPolygon]  # Only accept polygon layers
            )
        param.setHelp(
            "The input layer must:\n"
            "- Be a polygon layer (shape or geojson format).\n"
            "- Contain a single polygon outlining the Area-Of-Interest.\n"
            "- Use a compatible CRS (preferably WGS84/EPSG:3857 or 4326)."
        )
        self.addParameter(param)
        #1st output
        param = QgsProcessingParameterFileDestination(
                self.OUTPUT_BUILD,
                self.tr('Output file for buildings'),
                fileFilter="GeoJSON (*.geojson)",  # Filter for geojson files
                defaultValue=os.path.join(utils.default_save_directory(), "buildings.geojson")
            )
        param.setHelp(
            "Destination for output file containing buildings with BBR information.\n"
        )
        self.addParameter(param)
        #2nd output
        param_roads = QgsProcessingParameterFileDestination(
            self.OUTPUT_ROADS,
            self.tr('Output file for roads'),
            fileFilter="GeoJSON (*.geojson)",
            defaultValue=os.path.join(utils.default_save_directory(), "roads.geojson")
        )
        param_roads.setFlags(param_roads.flags() | QgsProcessingParameterDefinition.FlagOptional)
        param_roads.setHelp(
            "Destination for output file containing roads within AOI (optional).\n"
            "- For easier definition of pipe network."
        )
        self.addParameter(param_roads)

        self.addParameter(
            QgsProcessingParameterBoolean(
                "OPEN_OUTPUT",
                self.tr("Add output files to QGIS after running algorithm"),
                defaultValue=True  # Automatically checked
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        input_area_layer = self.parameterAsVectorLayer(parameters, self.INPUT_AREA, context)
        output_path = self.parameterAsFileOutput(parameters, self.OUTPUT_BUILD, context)
        output_roads_path = self.parameterAsFileOutput(parameters, self.OUTPUT_ROADS, context)
        open_output = self.parameterAsBoolean(parameters, "OPEN_OUTPUT", context)

        try:
            api_key = utils.read_datafordeler_api_key()
        except ValueError as e:
            raise QgsProcessingException(str(e))

        # Check input AOI layer
        feedback.pushInfo("Checking input layer ...")

        if not input_area_layer or not isinstance(input_area_layer, QgsVectorLayer):
            raise QgsProcessingException("Invalid input layer!")

        if input_area_layer.geometryType() != QgsWkbTypes.PolygonGeometry:
            raise QgsProcessingException("The input layer must be a polygon layer!")  
        features = list(input_area_layer.getFeatures())  # Check the feature count

        if len(features) != 1:
            raise QgsProcessingException("The input layer must contain exactly one polygon feature!")
        feature = features[0]  # Validate the geometry

        if not feature.isValid():
            raise QgsProcessingException("The input feature contains invalid geometry!")
        if feature.geometry().isEmpty():
            raise QgsProcessingException("The input feature has an empty geometry!")
        if not feature.geometry().isGeosValid():
            raise QgsProcessingException("The input feature geometry has errors!")

        # Common WFS settings
        wfs_base_url = "https://wfs.datafordeler.dk/GEODKV/GEODKV_WFS/1.0.0/WFS"
        service = "WFS"
        request = "GetFeature"
        version = "2.0.0"
        output_format = "application/json"
        startindex = 0
        count = 30000
        epsg = 25832  #crs code
        srsname = f"urn:ogc:def:crs:EPSG::{epsg}"
        target_crs_wfs = QgsCoordinateReferenceSystem(f"EPSG:{epsg}")
        output_crs = QgsCoordinateReferenceSystem("EPSG:4326")

        # --------------------------------------------------
        # STEP 1: BUILDINGS
        # --------------------------------------------------
        feedback.pushInfo("Retrieving buildings layer from WFS...")

        buildings_layer = None
        transformed_layer = None
        
        feedback.pushInfo("Input layer loaded successfully!")
        try:
            polygon_wkt_wfs = self.get_polygon_geometry(input_area_layer, target_crs_wfs)
            polygon_wkt_encoded = quote(polygon_wkt_wfs)

            layer_name = "geodkv_v001:bygning_current"
            complete_url = (
                f"{wfs_base_url}?apikey={api_key}"
                f"&SERVICE={service}&REQUEST={request}&VERSION={version}&TYPENAMES={layer_name}"
                f"&STARTINDEX={startindex}&COUNT={count}&SRSNAME={srsname}&OUTPUTFORMAT={output_format}"
                f"&CQL_FILTER=WITHIN(geometri,{polygon_wkt_encoded})"
            )

            response = rq.get(complete_url, timeout=(20, 120))           
            response.raise_for_status()

            # Write the GeoJSON response to GDAL's virtual memory filesystem so QGIS can read it
            gdal.FileFromMemBuffer('/vsimem/buildings.geojson', response.text.encode())
            buildings_layer = QgsVectorLayer('/vsimem/buildings.geojson', 'Buildings', 'ogr')

            # old version
            # buildings_layer = QgsVectorLayer(complete_url, "Buildings", "ogr")

            if not buildings_layer.isValid():
                raise QgsProcessingException(
                    f"The buildings layer could not be loaded from WFS. "
                    f"Check your DATAFORDELER_API_KEY and AOI geometry."
                )

            feedback.pushInfo("Buildings vector layer loaded successfully!")

            source_crs = buildings_layer.crs()
            transform = QgsCoordinateTransform(source_crs, output_crs, QgsProject.instance())

            transformed_layer = QgsVectorLayer("Polygon?crs=EPSG:4326", "Buildings_4326", "memory")
            transformed_provider = transformed_layer.dataProvider()
            transformed_provider.addAttributes(buildings_layer.fields())
            transformed_layer.updateFields()

            for feature in buildings_layer.getFeatures():
                new_feat = QgsFeature(transformed_layer.fields())
                new_feat.setAttributes(feature.attributes())
                geom = feature.geometry()
                geom.transform(transform)
                new_feat.setGeometry(geom)
                transformed_provider.addFeature(new_feat)

            transformed_layer.updateExtents()

            # Free the virtual memory now that all features have been copied to transformed_layer
            gdal.Unlink('/vsimem/buildings.geojson')

        except QgsProcessingException:
            raise
        except Exception as e:
            raise QgsProcessingException(
                f"Error while retrieving buildings: {str(e).replace(api_key, '<REDACTED>')}"
            )

        # --------------------------------------------------
        # STEP 2: BBR
        # --------------------------------------------------
        feedback.pushInfo("Retrieving BBR information...")
        bbr_attributes_by_uuid = self._fetch_bbr_attributes(transformed_layer, api_key, feedback)

        feedback.pushInfo("Adding BBR information to output file ...")

        new_fields = [
            QgsField("BuildYear", QMetaType.Type.Int),
            QgsField("BuildCode", QMetaType.Type.Int),
            QgsField("BBRArea", QMetaType.Type.Int),
            QgsField("BuildHeat", QMetaType.Type.Int),
            QgsField("FuelType", QMetaType.Type.Int)
        ]

        transformed_layer.startEditing()
        # transformed_provider already initialised in Step 1
        transformed_provider.addAttributes(new_fields)
        transformed_layer.updateFields()

        for feature in transformed_layer.getFeatures():
            attrs = bbr_attributes_by_uuid.get(feature["BBRUUID"], {})
            feature.setAttribute("BuildYear", attrs.get("BuildYear", 0))
            feature.setAttribute("BuildCode", attrs.get("BuildCode", 0))
            feature.setAttribute("BBRArea", attrs.get("BBRArea", 0))
            feature.setAttribute("BuildHeat", attrs.get("BuildHeat", 0))
            feature.setAttribute("FuelType", attrs.get("FuelType", 0))
            transformed_layer.updateFeature(feature)

        transformed_layer.commitChanges()

        # --------------------------------------------------
        # STEP 3: THERMONET FIELD
        # --------------------------------------------------
        self.thermonet(transformed_layer)

        # --------------------------------------------------
        # STEP 4: EXPORT BUILDINGS
        # --------------------------------------------------
        feedback.pushInfo("Exporting buildings to output file...")

        save_options = QgsVectorFileWriter.SaveVectorOptions()
        save_options.driverName = "GeoJSON"
        save_options.fileEncoding = "UTF-8"

        error = QgsVectorFileWriter.writeAsVectorFormatV3(
            transformed_layer,
            output_path,
            context.transformContext(),
            save_options
        )

        error_code = error[0] if isinstance(error, tuple) else error
        if error_code == QgsVectorFileWriter.NoError:
            feedback.pushInfo(f"Layer successfully exported to {output_path}")
        else:
            raise QgsProcessingException(f"Failed to export buildings layer. Error: {error}")

        if open_output:
            feedback.pushInfo("Opening building output file...")
            buildings_output_name = os.path.splitext(os.path.basename(output_path))[0]
            out_buildings_layer = QgsVectorLayer(output_path, buildings_output_name, "ogr")

            if not out_buildings_layer.isValid():
                raise QgsProcessingException("Could not load the building output layer!")

            QgsProject.instance().addMapLayer(out_buildings_layer)

            feedback.pushInfo("Applying symbology...")
            categories = []

            gray_symbol = QgsSymbol.defaultSymbol(out_buildings_layer.geometryType())
            gray_symbol.setColor(QColor(200, 200, 200))
            categories.append(QgsRendererCategory("No", gray_symbol, "No"))

            red_symbol = QgsSymbol.defaultSymbol(out_buildings_layer.geometryType())
            red_symbol.setColor(QColor(196, 60, 57))
            categories.append(QgsRendererCategory("Yes", red_symbol, "Yes"))

            renderer = QgsCategorizedSymbolRenderer("Thermonet", categories)
            out_buildings_layer.setRenderer(renderer)
            out_buildings_layer.triggerRepaint()

        # --------------------------------------------------
        # STEP 5: OPTIONAL ROADS
        # --------------------------------------------------
        roads_created = False

        if output_roads_path and output_roads_path != 'TEMPORARY_OUTPUT':
            feedback.pushInfo("")
            feedback.pushInfo("Retrieving roads within AOI and exporting to file ...")

            try:
                polygon_wkt_wfs = self.get_polygon_geometry(input_area_layer, target_crs_wfs)
                polygon_wkt_encoded = quote(polygon_wkt_wfs)

                road_layer_name = "geodkv_v001:vejmidte_current"
                roads_url = (
                    f"{wfs_base_url}?apikey={api_key}"
                    f"&SERVICE={service}&REQUEST={request}&VERSION={version}&TYPENAMES={road_layer_name}"
                    f"&STARTINDEX={startindex}&COUNT={count}&SRSNAME={srsname}&OUTPUTFORMAT={output_format}"
                    f"&CQL_FILTER=INTERSECTS(geometri,{polygon_wkt_encoded})"
                )

                response = rq.get(roads_url, timeout=(20, 120))           
                response.raise_for_status()

                # Write the GeoJSON response to GDAL's virtual memory filesystem so QGIS can read it
                gdal.FileFromMemBuffer('/vsimem/roads.geojson', response.text.encode())
                roads_layer = QgsVectorLayer('/vsimem/roads.geojson', 'Roads', 'ogr')

                # old version
                # roads_layer = QgsVectorLayer(roads_url, "Roads", "ogr")

                if not roads_layer.isValid():
                    feedback.pushInfo("Failed to load the roads vector layer from Datafordeler.")
                    feedback.pushInfo("Road output will be skipped, but building output is still OK.")
                else:
                    feedback.pushInfo("Roads vector layer loaded successfully!")

                    source_crs = roads_layer.crs()
                    transform = QgsCoordinateTransform(source_crs, output_crs, QgsProject.instance())

                    transformed_roads_layer = QgsVectorLayer("MultiLineString?crs=EPSG:4326", "Roads_4326", "memory")
                    transformed_roads_provider = transformed_roads_layer.dataProvider()
                    transformed_roads_provider.addAttributes(roads_layer.fields())
                    transformed_roads_layer.updateFields()

                    road_feature_count = 0
                    for feature in roads_layer.getFeatures():
                        new_feature = QgsFeature(transformed_roads_layer.fields())
                        new_feature.setAttributes(feature.attributes())
                        geom = feature.geometry()
                        geom.transform(transform)
                        new_feature.setGeometry(geom)
                        transformed_roads_provider.addFeature(new_feature)
                        road_feature_count += 1

                    transformed_roads_layer.updateExtents()

                    # Free the virtual memory now that all features have been copied to transformed_layer
                    gdal.Unlink('/vsimem/roads.geojson')

                    if road_feature_count == 0:
                        feedback.pushInfo("Road layer loaded, but no road features were found inside the AOI.")
                        feedback.pushInfo("Road output will be skipped.")
                    else:
                        dissolved_roads = processing.run(
                            "native:dissolve",
                            {
                                'INPUT': transformed_roads_layer,  # Your roads layer
                                'FIELD': [],  # Empty list = dissolve all features into one
                                'OUTPUT': 'memory:'  # Use memory layer for temporary result
                            },
                            context=context,
                            feedback=feedback
                        )
                        dissolved_roads_layer = dissolved_roads['OUTPUT']

                        clipped_roads = processing.run(
                            "native:clip",
                            {
                                'INPUT': dissolved_roads_layer,
                                'OVERLAY': input_area_layer,
                                'OUTPUT': 'memory:'
                            },
                            context=context,
                            feedback=feedback
                        )
                        clipped_roads_layer = clipped_roads['OUTPUT']

                        split_roads = processing.run(
                            "native:splitwithlines",
                            {
                                'INPUT': clipped_roads_layer,
                                'LINES': clipped_roads_layer,
                                'OUTPUT': 'memory:'
                            },
                            context=context,
                            feedback=feedback
                        )
                        split_roads_layer = split_roads['OUTPUT']

                        if split_roads_layer is None or split_roads_layer.featureCount() == 0:
                            feedback.pushInfo("Road processing returned no final features.")
                            feedback.pushInfo("Road output will be skipped.")
                        else:
                            # Create new ouput layer with geometry only
                            crs = split_roads_layer.crs()
                            new_roads_layer = QgsVectorLayer(
                                f'MultiLineString?crs={crs.authid()}',
                                "Dissolved Roads (No Fields)",
                                "memory"
                            )
                            provider = new_roads_layer.dataProvider()

                            for feature in split_roads_layer.getFeatures():
                                new_feature = QgsFeature()
                                new_feature.setGeometry(feature.geometry())
                                provider.addFeature(new_feature)

                            new_roads_layer.updateExtents()

                            save_options = QgsVectorFileWriter.SaveVectorOptions()
                            save_options.driverName = "GeoJSON"
                            save_options.fileEncoding = "UTF-8"

                            error = QgsVectorFileWriter.writeAsVectorFormatV3(
                                new_roads_layer,
                                output_roads_path,
                                context.transformContext(),
                                save_options
                            )

                            error_code = error[0] if isinstance(error, tuple) else error
                            if error_code == QgsVectorFileWriter.NoError:
                                feedback.pushInfo(f"Layer successfully exported to {output_roads_path}")
                                roads_created = True
                            else:
                                feedback.pushInfo(f"Failed to export the roads layer. Error: {error}")

            except Exception as e:
                feedback.pushInfo(f"Road processing failed: {str(e).replace(api_key, '<REDACTED>')}")
                feedback.pushInfo("Building output is still completed successfully.")

            # Open road layer only if it was actually created
            if open_output and roads_created and os.path.exists(output_roads_path):
                feedback.pushInfo("Opening roads output file...")
                roads_output_name = os.path.splitext(os.path.basename(output_roads_path))[0]
                out_roads_layer = QgsVectorLayer(output_roads_path, roads_output_name, "ogr")

                if out_roads_layer.isValid():
                    QgsProject.instance().addMapLayer(out_roads_layer)
                    line_symbol = QgsLineSymbol.createSimple({
                        'color': 'black',
                        'width': '1.1',
                    })
                    out_roads_layer.setRenderer(QgsSingleSymbolRenderer(line_symbol))
                    out_roads_layer.triggerRepaint()
                else:
                    feedback.pushInfo("Road output file exists, but QGIS could not load it.")

        feedback.pushInfo("Processing completed successfully.")

        result = {self.OUTPUT_BUILD: output_path}
        if roads_created:
            result[self.OUTPUT_ROADS] = output_roads_path
        return result

    def get_polygon_geometry(self, input_layer, target_crs):
        """
        Function to get the geometry of a single polygon feature from the
        input layer and transform it.
        """
        features = list(input_layer.getFeatures())
        feature = features[0]
        geom = feature.geometry()

        if input_layer.crs() != target_crs:
            transform = QgsCoordinateTransform(input_layer.crs(), target_crs, QgsProject.instance())
            geom.transform(transform)

        return geom.asWkt()

    def thermonet(self, layer):
        """
        Adds a 'Thermonet' field to the layer using an expression,
        with values based on the 'BBRUUID' field.
        """
        layer_provider = layer.dataProvider()
        if layer_provider.fields().indexFromName("Thermonet") == -1:
            layer_provider.addAttributes([QgsField("Thermonet", QMetaType.Type.QString)])
            layer.updateFields()

        expression = QgsExpression(
            'CASE WHEN "BBRUUID" IS NOT NULL AND "BBRArea" <> 0 AND "BuildCode" < 200 THEN \'Yes\' ELSE \'No\' END'
        )
        expr_context = QgsExpressionContext()
        expr_context.appendScopes(QgsExpressionContextUtils.globalProjectLayerScopes(layer))

        with edit(layer):
            for feature in layer.getFeatures():
                expr_context.setFeature(feature)
                thermonet_value = expression.evaluate(expr_context)
                if expression.hasEvalError():
                    raise QgsProcessingException(f"Expression evaluation error: {expression.evalErrorString()}")
                feature.setAttribute("Thermonet", thermonet_value)
                layer.updateFeature(feature)

    def _fetch_bbr_attributes(self, layer, api_key, feedback):
        """Fetch BBR building attributes for every feature's BBRUUID, batched.

        Queries the BBR entity-based WFS (``bbr_v001:bygning_current``) via
        POST requests, chunking BBRUUIDs into batches of at most
        ``max_batch_size``. POST (rather than GET) is required above
        roughly 150 IDs per request: this WFS's server caps HTTP header
        size at ~8KB, and GET puts the CQL_FILTER in the URL/request line,
        while POST moves it into the request body instead.

        Parameters
        ----------
        layer : QgsVectorLayer
            The buildings layer; each feature must have a 'BBRUUID' field.
        api_key : str
            Datafordeler API key.
        feedback : QgsProcessingFeedback
            Used to report per-batch progress and support cancellation.

        Returns
        -------
        dict[str, dict[str, int]]
            Maps each BBRUUID to its BuildYear/BuildCode/BBRArea/BuildHeat/
            FuelType values. A BBRUUID with no matching BBR record is
            simply absent from the returned mapping.

        Raises
        ------
        QgsProcessingException
            If a batch request times out or otherwise fails.
        """
        bbr_url = "https://wfs.datafordeler.dk/BBR/BBR_WFS/1.0.0/WFS"
        bbr_typename = "bbr_v001:bygning_current"
        max_batch_size = 200

        if not any(layer.getFeatures()):
            raise QgsProcessingException("No buildings found within the AOI!")

        uuids = [feature["BBRUUID"] for feature in layer.getFeatures() if feature["BBRUUID"]]
        unique_uuids = list(dict.fromkeys(uuids))
        if not unique_uuids:
            return {}

        batches = [
            unique_uuids[i:i + max_batch_size]
            for i in range(0, len(unique_uuids), max_batch_size)
        ]

        attributes_by_uuid = {}
        for batch_index, batch_uuids in enumerate(batches):
            if feedback.isCanceled():
                break

            id_list = ",".join(f"'{uuid}'" for uuid in batch_uuids)
            body = {
                "service": "WFS",
                "request": "GetFeature",
                "typeName": bbr_typename,
                "outputFormat": "application/json",
                "CQL_FILTER": f"id_lokalId IN ({id_list})",
            }

            try:
                response = rq.post(f"{bbr_url}?apikey={api_key}", data=body, timeout=(20, 120))
                response.raise_for_status()
                data = response.json()
            except rq.exceptions.Timeout:
                raise QgsProcessingException(
                    f"BBR request timed out for batch {batch_index + 1}/{len(batches)}"
                )
            except rq.exceptions.RequestException as e:
                raise QgsProcessingException(
                    f"BBR request failed for batch {batch_index + 1}/{len(batches)}: "
                    f"{str(e).replace(api_key, '<REDACTED>')}"
                )

            for wfs_feature in data.get("features", []):
                properties = wfs_feature.get("properties", {})
                uuid = properties.get("id_lokalId")
                if not uuid:
                    continue
                attributes_by_uuid[uuid] = {
                    "BuildYear": properties.get("byg026Opførelsesår") or 0,
                    "BuildCode": properties.get("byg021BygningensAnvendelse") or 0,
                    "BBRArea": properties.get("byg038SamletBygningsareal") or 0,
                    "BuildHeat": properties.get("byg056Varmeinstallation") or 0,
                    "FuelType": properties.get("byg057Opvarmningsmiddel") or 0,
                }

            feedback.pushInfo(
                f"Fetched BBR data for batch {batch_index + 1}/{len(batches)} "
                f"({len(batch_uuids)} buildings)"
            )
            feedback.setProgress(int(100 * (batch_index + 1) / len(batches)))

        return attributes_by_uuid

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'get_buildings_and_bbr'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('Get Buildings and BBR Information')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '1. Heatloads'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def icon(self):
        return QIcon(utils.get_logo('logo2.png'))

    def shortHelpString(self):
        return (
            "<p><b> This tool: </b> <p>"
            "<p> 1. Retrieves all buildings within the input AOI polygon from a WFS. "
            "The buildings layer contains a field 'BBRUUID', which is used to "
            "retrieve BBR information for automatic"
            " calculation of heatloads in a later step. <p>"
            "<p> 2. Retrieves building information from the BBR database: "
            "BuildYear ('byg026Opførelsesår'), BuildCode ('byg021BygningensAnvendelse'), "
            " BBRArea ('byg038SamletBygningsareal'), BuildHeat('byg056Varmeinstallation') "
            "and FuelType('byg057Opvarmningsmiddel'). Key to the codes can "
            "be found at https://teknik.bbr.dk/kodelister (in Danish) <p>"
            "<p> 3. Adds a variable/field 'Thermonet' that is set to 'No' if "
            "the building has 'BBRUUID' = NULL, 'BBRArea' = 0, or 'BuildCode' > 200. <p>"
            "<p> 4. Stores the buildings in a new file.<p>"
            "<p> 5. Optionally tries to retrieve roads and export them as a separate file.<p>"
            "<p> <b>Please note:</b> This tool requires a Datafordeler API key, set as "
            "DATAFORDELER_API_KEY in a .env file next to the plugin (copy .env-template to "
            ".env and fill it in). Create an IT-system with API-key authentication via "
            "Datafordeler's Administration portal at https://datafordeler.dk/ to obtain one. <p>"
        )

    def createInstance(self):
        return GetBuildingsAndBBRAlgorithm()

        
