# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QThermonet
                                 A QGIS plugin
 This plugin links QGIS to pythermonet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-10
        copyright            : (C) 2024 by Jane Lund Andersen/VIA University College
        email                : jana@via.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Jane Lund Andersen/VIA University College'
__date__ = '2025-06-10'
__copyright__ = '(C) 2025 by Jane Lund Andersen/VIA University College'


from qgis.core import (
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsFeature,
    QgsFeatureRequest,
    QgsField,
    QgsFields,
    QgsGeometry,
    QgsProcessing,
    QgsProcessingAlgorithm,
    QgsProcessingException,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterDefinition,
    QgsProcessingParameterFileDestination,
    QgsProcessingParameterVectorLayer,
    QgsProject,
    QgsVectorFileWriter,
    QgsVectorLayer,
    QgsWkbTypes
)
from collections import Counter
from qgis.PyQt.QtCore import QCoreApplication, QMetaType
from qgis.PyQt.QtGui import QIcon
from qgis import processing
import os
import inspect
from .. import output_handling, utils
from .main_pipe_hierarchy_algorithm import get_connection_node_geometry, style_main_pipes

#: A service pipe within this distance of a main pipe is tied in to it -- the
#: same tolerance the topology uses to collect heat pump IDs.
_TIE_IN_TOLERANCE = 0.1  # m
#: Main pipes within this distance of each other are connected -- the same
#: tolerance the topology uses for "downstream" pipes.
_JUNCTION_TOLERANCE = 1.0  # m
#: Cut-offs shorter than this are floating-point noise, not tails.
_MIN_CROP_LENGTH = 0.001  # m


def _merge_to_line(geometry):
    """`geometry` as one single-part line, or `None` if its parts don't join up."""
    merged = geometry.mergeLines() if geometry.isMultipart() else QgsGeometry(geometry)
    if merged.isEmpty() or merged.isMultipart():
        return None
    return merged


def _crop_network(pipes, service_geometries, node_point, distance_area):
    """Remove main pipes without heat pumps and trim pipe ends past their last connection.

    A pipe is in use if a service pipe is tied in to it or to a pipe
    downstream of it (away from the source). Unused pipes are removed; each
    kept pipe is cut to the stretch between its first and last "keep" point:
    service-pipe tie-ins, junctions with kept pipes, and -- on the root pipe
    -- the source's connection node. See
    `claude/handoffs/2026-10-09-network-cropping-design.md`.

    Parameters
    ----------
    pipes : list of tuple(int, QgsGeometry, int)
        ``(feature id, geometry, Level)`` of each main pipe.
    service_geometries : list of QgsGeometry
        The service pipes, in the main pipes' CRS.
    node_point : QgsPointXY
        The source's connection node, in the main pipes' CRS.
    distance_area : QgsDistanceArea
        Ellipsoidal calculator for the reported lengths (metres).

    Returns
    -------
    kept : dict[int, QgsGeometry]
        New geometry per kept feature id (unchanged pipes included).
    report : list of tuple(str, float, str)
        ``(action, length in m, text)`` per removed pipe, trimmed end or
        pipe left as is (see `_describe`).
    """
    geometries = {fid: geometry for fid, geometry, _ in pipes}
    levels = {fid: level for fid, _, level in pipes}

    # Tie-in points per pipe (where on the pipe each service pipe connects)
    tie_ins = {fid: [] for fid in geometries}
    for service in service_geometries:
        for fid, geometry in geometries.items():
            if geometry.distance(service) <= _TIE_IN_TOLERANCE:
                tie_ins[fid].append(geometry.nearestPoint(service).asPoint())

    neighbours = {
        fid: [
            other for other in geometries
            if other != fid and geometries[fid].distance(geometries[other]) <= _JUNCTION_TOLERANCE
        ]
        for fid in geometries
    }

    # Walk outwards from the root pipe (nearest the source) to find parents
    node_geometry = QgsGeometry.fromPointXY(node_point)
    root = min(geometries, key=lambda fid: geometries[fid].distance(node_geometry))
    parent = {root: None}
    order = [root]
    for fid in order:
        for other in neighbours[fid]:
            if other not in parent:
                parent[other] = fid
                order.append(other)

    # In use: own tie-in, or a child in use (decided from the leaves inwards).
    # Pipes the walk never reached aren't connected to the source at all.
    in_use = {fid: bool(tie_ins[fid]) for fid in order}
    for fid in reversed(order):
        if in_use[fid] and parent[fid] is not None:
            in_use[parent[fid]] = True

    report = []
    kept = {}
    for fid, geometry in geometries.items():
        if fid not in parent:
            # Not connected to the source (Main Pipe Hierarchy warns about
            # these too) -- left as is rather than dropping its buildings.
            report.append(_describe(
                "Not connected to the source, left as is", geometry, levels[fid], distance_area
            ))
            kept[fid] = geometry
            continue
        if not in_use[fid]:
            report.append(_describe("Removed a main pipe without heat pumps", geometry, levels[fid], distance_area))
            continue

        keep_points = list(tie_ins[fid])
        keep_points += [
            geometry.nearestPoint(geometries[other]).asPoint()
            for other in neighbours[fid] if in_use.get(other, False)
        ]
        if fid == root:
            keep_points.append(geometry.nearestPoint(node_geometry).asPoint())

        line = _merge_to_line(geometry)
        if line is None:
            report.append(_describe(
                "Not trimmed (its parts don't form one line)", geometry, levels[fid], distance_area
            ))
            kept[fid] = geometry
            continue

        positions = [line.lineLocatePoint(QgsGeometry.fromPointXY(point)) for point in keep_points]
        start, end, total = min(positions), max(positions), line.length()
        curve = line.constGet()
        used = QgsGeometry(curve.curveSubstring(start, end))
        if distance_area.measureLength(used) < _MIN_CROP_LENGTH:
            # Its only connection sits on its junction -- nothing to dimension
            report.append(_describe("Removed a main pipe without heat pumps", geometry, levels[fid], distance_area))
            continue
        for cut_from, cut_to in ((0.0, start), (end, total)):
            cut = QgsGeometry(curve.curveSubstring(cut_from, cut_to))
            if distance_area.measureLength(cut) >= _MIN_CROP_LENGTH:
                report.append(_describe("Trimmed the end of a main pipe", cut, levels[fid], distance_area))
        kept[fid] = used

    return kept, report


def _describe(action, geometry, level, distance_area) -> tuple[str, float, str]:
    """One report entry: ``(action, length in m, text with Level, length and midpoint)``."""
    length = distance_area.measureLength(geometry)
    midpoint = geometry.interpolate(geometry.length() / 2).asPoint()
    text = f"{action} (Level {level}, {length:.2f} m, midpoint at {midpoint.x():.1f}, {midpoint.y():.1f})"
    return action, length, text


class PipeTopologyAlgorithm(QgsProcessingAlgorithm):
    
    #Handle input/output
    PIPES_LAYER = "PIPES_LAYER"
    SERVICE_PIPES_LAYER = "SERVICE_PIPES_LAYER"
    SOURCE_LAYER = "SOURCE_LAYER"
    CROP_NETWORK = "CROP_NETWORK"
    CROP_MAINS_FILE = "CROP_MAINS_FILE"
    #: Hidden; where to write the cropped main pipes when run as a step
    #: (standalone, they're written back to the main pipes input file).
    CROPPED_MAINS_OUTPUT = "CROPPED_MAINS_OUTPUT"
    OUTPUT = "OUTPUT"
    DAT_OUTPUT = "DAT_OUTPUT"
    #: Hidden; `True` when Build Pipe Network runs this tool as one of its
    #: steps -- then no overwrite pop-up, no temp-file swap, no path caching
    #: and no layer loading (see output_handling.OutputSet's step mode).
    RUN_AS_STEP = "RUN_AS_STEP"

    def initAlgorithm(self, config=None):
        
        #1st input
        param=QgsProcessingParameterVectorLayer(
                self.PIPES_LAYER,
                "Select the Pipes Layer",
                [QgsProcessing.TypeVectorLine],
                defaultValue=utils.get_cached_path("mains_file"),
            )
        param.setHelp(
            "The input layer must:\n"
            "- contain the main pipes network of the thermonet.\n"
            "- Contain the required fields: 'Level' that defines the hierarchy of the pipe-heatpump connections.\n"
            "- Any CRS works; a projected CRS in metres (e.g. EPSG:25832) is recommended."
        )

        self.addParameter(param)
        
        #2nd input
        param = QgsProcessingParameterVectorLayer(
                self.SERVICE_PIPES_LAYER,
                "Select the Service Pipes Layer",
                [QgsProcessing.TypeVectorLine],
                defaultValue=utils.get_cached_path("service_pipes_file"),
            )
        param.setHelp(
            "The service pipes layer must:\n"
            "- contain the service pipes connecting the heatpumps to the main thermonet pipes.\n"
            "- Contain the heatpump ID's of the heatpumps in field with name 'id_lokalId' \n"
            "- Any CRS works; a projected CRS in metres (e.g. EPSG:25832) is recommended."
        )

        self.addParameter(param)

        # Only needed for cropping: the root pipe must keep its stretch from
        # the source to the first building (it carries all the flow).
        param = QgsProcessingParameterVectorLayer(
                self.SOURCE_LAYER,
                "Select the source placement layer",
                [QgsProcessing.TypeVectorPoint, QgsProcessing.TypeVectorLine],
                defaultValue=utils.get_cached_path("source_file"),
                optional=True,
            )
        param.setHelp(
            "The output of the 'Source Placement' tool (BHE point layer or HHE trench "
            "line layer, with an 'is_connection_node' attribute). Needed when "
            "'Remove main pipes without heat pumps' is ticked."
        )
        self.addParameter(param)

        param = QgsProcessingParameterBoolean(
            self.CROP_NETWORK, "Remove main pipes without heat pumps", defaultValue=True
        )
        param.setHelp(
            "Removes main pipes with no heat pumps on them or downstream, and trims "
            "the end of a pipe past its last connection -- such pipes carry no flow. "
            "Unticked, a main pipe without heat pumps stops the run with an error."
        )
        self.addParameter(param)

        param = QgsProcessingParameterBoolean(
            self.CROP_MAINS_FILE, "Also crop the main pipe hierarchy file", defaultValue=False
        )
        param.setHelp(
            "Also writes the cropped main pipes back to the main pipes input file. "
            "Unticked, only the topology outputs are cropped, so comparing the two "
            "layers shows what was removed."
        )
        self.addParameter(param)

        #output geojson
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT,
                self.tr('Output GeoJSON'),
                fileFilter="GeoJSON (*.geojson)",  # Filter for file type
                defaultValue=os.path.join(utils.default_save_directory(), "pipe_topology.geojson")
            )
        )

        #output dat-format
        self.addParameter(
            QgsProcessingParameterFileDestination(
                "DAT_OUTPUT",
                self.tr("Output DAT file"),
                fileFilter="DAT files (*.dat)",
                defaultValue=os.path.join(utils.default_save_directory(), "pipe_topology.dat")
            )
        )

        param = QgsProcessingParameterBoolean(self.RUN_AS_STEP, "Run as a step", defaultValue=False)
        param.setFlags(param.flags() | QgsProcessingParameterDefinition.FlagHidden)
        self.addParameter(param)

        param = QgsProcessingParameterFileDestination(
            self.CROPPED_MAINS_OUTPUT, "Cropped main pipes (step mode)",
            fileFilter="GeoJSON (*.geojson)", optional=True,
        )
        param.setFlags(param.flags() | QgsProcessingParameterDefinition.FlagHidden)
        self.addParameter(param)

    def checkParameterValues(self, parameters, context):
        """Require a source layer when cropping is on.

        Parameters
        ----------
        parameters : dict
            The run's parameter values.
        context : QgsProcessingContext
            The run's context.

        Returns
        -------
        tuple[bool, str]
            ``(True, "")`` if the run can start, else ``(False, message)``.

        """
        ok, message = super().checkParameterValues(parameters, context)
        if not ok:
            return ok, message
        if (
            self.parameterAsBoolean(parameters, self.CROP_NETWORK, context)
            and self.parameterAsVectorLayer(parameters, self.SOURCE_LAYER, context) is None
        ):
            return False, (
                "'Remove main pipes without heat pumps' needs the source placement layer "
                "(to keep the pipe stretch between the source and the first building). "
                "Select it, or untick the option."
            )
        if self._crops_mains_file(parameters, context) and not self.parameterAsBoolean(
            parameters, self.RUN_AS_STEP, context
        ) and self._mains_file_path(parameters, context) is None:
            return False, (
                "'Also crop the main pipe hierarchy file' needs the main pipes layer to be "
                "a file (e.g. main_pipe_hierarchy.geojson), not a temporary layer."
            )
        return True, ""

    def _crops_mains_file(self, parameters, context) -> bool:
        return self.parameterAsBoolean(parameters, self.CROP_NETWORK, context) and self.parameterAsBoolean(
            parameters, self.CROP_MAINS_FILE, context
        )

    def _mains_file_path(self, parameters, context) -> str | None:
        """The main pipes input's file path, or None if it isn't a file-based layer."""
        layer = self.parameterAsVectorLayer(parameters, self.PIPES_LAYER, context)
        if layer is None or layer.providerType() != "ogr":
            return None
        path = layer.source().split("|", 1)[0]
        return path if os.path.isfile(path) else None

    def prepareAlgorithm(self, parameters, context, feedback):
        if not utils.prepare_algorithm_project_setup(self, parameters, context, feedback, self.PIPES_LAYER):
            return False
        if not self.parameterAsBoolean(parameters, self.RUN_AS_STEP, context):
            paths = [
                self.parameterAsFileOutput(parameters, self.OUTPUT, context),
                self.parameterAsFileOutput(parameters, "DAT_OUTPUT", context),
            ]
            if self._crops_mains_file(parameters, context):
                paths.append(self._mains_file_path(parameters, context))
            if not output_handling.confirm_overwrite(paths):
                feedback.reportError("Cancelled -- no files were changed.")
                return False
        return True

    def processAlgorithm(self, parameters, context, feedback):
        output_path = self.parameterAsFileOutput(parameters, self.OUTPUT, context)
        dat_output_path = self.parameterAsFileOutput(parameters, "DAT_OUTPUT", context)
        self._outputs = output_handling.OutputSet(
            step_mode=self.parameterAsBoolean(parameters, self.RUN_AS_STEP, context)
        )
        geojson_temp_path = self._outputs.add_file(
            output_path,
            layer_name="Pipe topology",
            cache_roles=["topology_geojson_file"],
        )
        dat_temp_path = self._outputs.add_file(dat_output_path, cache_roles=["topology_dat_file"])
        cropped_mains_path = None
        if self._crops_mains_file(parameters, context):
            if self.parameterAsBoolean(parameters, self.RUN_AS_STEP, context):
                cropped_mains_path = self.parameterAsFileOutput(parameters, self.CROPPED_MAINS_OUTPUT, context) or None
            else:
                cropped_mains_path = self._outputs.add_file(
                    self._mains_file_path(parameters, context),
                    layer_name="Main pipe hierarchy",
                    cache_roles=["mains_file"],
                    style_default=style_main_pipes,
                )
        try:
            self._run(parameters, context, feedback, geojson_temp_path, dat_temp_path, cropped_mains_path)
            if feedback.isCanceled():
                raise QgsProcessingException("Cancelled -- no files were changed.")
        except Exception:
            self._outputs.discard()
            raise
        return {
            self.OUTPUT: output_path,
            "DAT_OUTPUT": dat_output_path,
        }

    def postProcessAlgorithm(self, context, feedback):
        self._outputs.commit(feedback)
        return {}

    def _run(self, parameters, context, feedback, output_path, dat_output_path, cropped_mains_path=None):
        """Build the topology and write the outputs to the given (temp) paths.

        `cropped_mains_path`: also write the cropped main pipes there (only
        when cropping is on and "Also crop the main pipe hierarchy file").
        """
        pipes_layer = self.parameterAsVectorLayer(parameters, self.PIPES_LAYER, context)
        service_pipes_layer = self.parameterAsVectorLayer(parameters, self.SERVICE_PIPES_LAYER, context)


        if not pipes_layer or not service_pipes_layer:
            raise QgsProcessingException("Invalid input layers!")

        ## Step 0: Re-project layers if necessarty (units should be meters for algorithm to work)
        default_projected_crs = QgsCoordinateReferenceSystem(utils.project_crs_choice())

        # Use the input's own CRS if it's metric (not degrees, not EPSG:3857)
        if utils.needs_metric_reprojection(pipes_layer.crs()):
            feedback.pushInfo(f"Pipes layer is not in metres ({pipes_layer.crs().authid()}), reprojecting to {default_projected_crs.authid()}")
            pipes_layer_proj = processing.run(
                "native:reprojectlayer",
                {
                    'INPUT': pipes_layer,
                    'TARGET_CRS': default_projected_crs,
                    'OUTPUT': 'memory:'
                },
                context=context,
                feedback=feedback
            )['OUTPUT']
        else:
            feedback.pushInfo(f"Pipes layer is already projected: {pipes_layer.crs().authid()}")
            pipes_layer_proj = pipes_layer
        
        # Do the same for source layer
        if utils.needs_metric_reprojection(service_pipes_layer.crs()):
            feedback.pushInfo(f"Service pipes layer is not in metres ({service_pipes_layer.crs().authid()}), reprojecting to {pipes_layer_proj.crs().authid()}")
            service_pipes_layer_proj = processing.run(
                "native:reprojectlayer",
                {
                    'INPUT': service_pipes_layer,
                    'TARGET_CRS': pipes_layer_proj.crs(),  # ensure it matches pipes
                    'OUTPUT': 'memory:'
                },
                context=context,
                feedback=feedback
            )['OUTPUT']
        else:
            feedback.pushInfo(f"Source layer is already projected: {service_pipes_layer.crs().authid()}")
            service_pipes_layer_proj = service_pipes_layer

        # ...then a final check catches the remaining case: both already
        # projected (so neither branch above ran), but in two different
        # projected CRSs -- the 0.1 m service-pipe search below would then
        # compare coordinates from different systems and find nothing.
        # Same check as service_pipes_algorithm.py.
        if service_pipes_layer_proj.crs() != pipes_layer_proj.crs():
            feedback.pushInfo(
                f"Service pipes layer ({service_pipes_layer_proj.crs().authid()}) and pipes layer "
                f"({pipes_layer_proj.crs().authid()}) are in different CRSs, reprojecting "
                f"service pipes layer to match pipes layer."
            )
            service_pipes_layer_proj = processing.run(
                "native:reprojectlayer",
                {
                    'INPUT': service_pipes_layer_proj,
                    'TARGET_CRS': pipes_layer_proj.crs(),
                    'OUTPUT': 'memory:'
                },
                context=context,
                feedback=feedback
            )['OUTPUT']

        # A cancelled reprojection returns an empty layer -- stop here with a
        # clear message instead of failing further down on the empty input.
        if feedback.isCanceled():
            raise QgsProcessingException("Cancelled -- no files were changed.")
        if pipes_layer_proj.featureCount() == 0:
            raise QgsProcessingException("The pipes layer has no features.")

        # Define the fields for the output layer
        feedback.pushInfo("Creating the new fields ...")
        fields = QgsFields()
        
        # List of fields to add: name, type, length, precision (if applicable)
        field_definitions = [
            ("Section", QMetaType.Type.QString, 255, 0), # String field, length 255
            ("SDR", QMetaType.Type.Int, 0, 0),          # Integer field
            ("Trace_(m)", QMetaType.Type.Double, 4, 2), # Double field with 2 decimal places
            ("Number_of_traces", QMetaType.Type.Int, 0, 0),   # Integer field
            ("Max_pressure_loss_(Pa)", QMetaType.Type.Int, 0, 0),   # Integer field
            ("HP_ID_vector", QMetaType.Type.QString, 0, 0),  # String field
        ]
        
        # Add fields to the QgsFields object
        for field_name, field_type, field_length, field_precision in field_definitions:
            new_field = QgsField(field_name, field_type, len=field_length, prec=field_precision)
            fields.append(new_field)

        # Set CRS from the service_pipes_layer
        crs = service_pipes_layer_proj.crs()

        # Collected in memory and written in one go at the end -- so no
        # output file is open while the checks below can still raise (an
        # open file couldn't be cleaned up after a failure on Windows).
        out_features = []
        dat_lines = ["Section\tSDR\tTrace_(m)\tNumber_of_traces\tMax_pressure_loss_(Pa)\tHP_ID_vector\n"]

        # Ellipsoidal, in metres -- a plain $length is planar in CRS units.
        # Both layers are in the pipes' CRS by now (reprojected above).
        distance_area = utils.create_distance_area(pipes_layer_proj.crs(), context.transformContext())

        # The heat pump IDs are copied from the buildings layer by Service
        # Pipes; they link the topology to the heat loads file.
        if "id_lokalId" not in service_pipes_layer_proj.fields().names():
            raise QgsProcessingException(
                "The service pipes layer has no 'id_lokalId' field with the heat pump IDs. "
                "Run Shortest Service Pipes with a buildings layer that has it (e.g. the "
                "Get Buildings or Heat Loads output), then run Pipe Topology again."
            )

        if self.parameterAsBoolean(parameters, self.CROP_NETWORK, context):
            pipes_layer_proj = self._crop_pipes(
                parameters, context, feedback, pipes_layer_proj, service_pipes_layer_proj, distance_area,
                cropped_mains_path,
            )

        # Copy features from the service pipes layer
        feedback.pushInfo("Handling service pipes ...")
        pipeNo = 0
        for feature in service_pipes_layer_proj.getFeatures():
            pipeNo += 1
            new_feature = QgsFeature(fields)
            new_feature.setGeometry(feature.geometry())
            
            Trace_length = distance_area.measureLength(feature.geometry())
            utils.raise_if_nan(Trace_length, "a pipe length")

            #Update field values
            new_feature["Section"] = "Service_pipe_" + str(pipeNo)
            new_feature["SDR"] = 17
            new_feature["Trace_(m)"] = Trace_length
            new_feature["Number_of_traces"] = 1
            new_feature["Max_pressure_loss_(Pa)"] = 180 * Trace_length
            new_feature["HP_ID_vector"] = feature["id_lokalId"]
            out_features.append(new_feature)

            # Update dat file
            dat_lines.append(
                f"{new_feature['Section']}\t{new_feature['SDR']}\t"
                f"{float(new_feature['Trace_(m)']):.2f}\t"  # Explicitly format to 2 decimal places
                f"{new_feature['Number_of_traces']}\t"
                f"{int(round(new_feature['Max_pressure_loss_(Pa)']))}\t"  # Ensure integer for MaxPLossPa
                f"{new_feature['HP_ID_vector']}\n"
            )
        
        # Copy features from the pipes layer
        feedback.pushInfo("Handling main pipes ...")
        
        # Validate that the 'Level' field exists and all features have valid integer values
        if "Level" not in [field.name() for field in pipes_layer_proj.fields()]:
            raise QgsProcessingException(
                "The 'Level' field is missing in the input pipes layer. "
                "Please ensure a 'Level' field is created and contains integer values "
                "representing the hierarchy of the pipe topology. Each feature in the layer must have a "
                "valid integer value in the 'Level' field before running this algorithm."
            )
            
        # Check that all features have valid integer values in the 'Level' field
        invalid_features = []
        for feature in pipes_layer_proj.getFeatures():
            level_value = feature["Level"]
            if not isinstance(level_value, int):
                invalid_features.append(feature.id())
        
        if invalid_features:
            raise QgsProcessingException(
                f"The following features have invalid or missing values in the 'Level' field: {invalid_features}. "
                "Ensure all features in the 'Level' field contain valid integer values before running this algorithm."
            )

        # Find the lowest level pipes
        max_level = max([feature["Level"] for feature in pipes_layer_proj.getFeatures()])
        
        # Set up sorting of main pipes so topology is handled correctly when assigning Heat-pump ID's
        order_by_clause = QgsFeatureRequest.OrderByClause("Level", ascending=False)
        order_by = QgsFeatureRequest.OrderBy([order_by_clause])
        request = QgsFeatureRequest().setOrderBy(order_by)
        
        # Dictionary to store HP_IDs for processed features
        processed_features = {}

        pipeNo = 0
        # Iterate through the sorted features
        for pipe_feature in pipes_layer_proj.getFeatures(request):
            current_level = pipe_feature["Level"]
            feedback.pushInfo(f"Processing pipe with Level: {current_level}")

            pipeNo += 1
            new_feature = QgsFeature(fields)
            new_feature.setGeometry(pipe_feature.geometry())
            
            # Step 1: calculate the length of the current pipe
            Trace_length = distance_area.measureLength(pipe_feature.geometry())
            utils.raise_if_nan(Trace_length, "a pipe length")
            
            
            # Step 2: Retrieve Heat-pump ID's for each pipe
            feedback.pushInfo("") #Empty line for visibility of output
            feedback.pushInfo(f"Retrieving heatpump ID's for pipe {pipeNo} ... ")
            
            # Find nearby service pipes
            Dist = 0.1 # distance in meter, to ensure robustness for near-overlapping features
            nearby_service_pipes = self.find_features_within_distance(pipe_feature, service_pipes_layer_proj, Dist)
            
            # Collect IDs of the nearby service pipes
            connected_ids = []
            for f in nearby_service_pipes:
                connected_ids.append(f["id_lokalId"])
                feedback.pushInfo(f"Service pipe ID found: {f['id_lokalId']}")

            # Kept as a list (joined only when written out) so an empty
            # contribution can't leave a stray ", " in the HP_ID_vector.
            ids_list = [str(hp_id) for hp_id in connected_ids]

            # Print or assign the result
            feedback.pushInfo(f"Pipe ID: {pipe_feature.id()}, Connected Service Pipes: {', '.join(ids_list)}")
            
            
            # Add HP ID's of lower-level connected pipes
            if current_level < max_level:
                # Find pipes with higher levels within 1 meter of the current feature
                higher_level_ids = []
                for other_feature in pipes_layer_proj.getFeatures():
                    other_level = other_feature["Level"]
                    
                    # Check if the other feature has a higher level and is within 1 meter
                    if other_level > current_level:
                        distance = pipe_feature.geometry().distance(other_feature.geometry())
                        if distance <= 1:  # 1 meter threshold - lower?
                            # Retrieve HP_IDs for the other feature from the processed_features dictionary
                            other_id = other_feature.id()
                            if other_id in processed_features:
                                higher_level_ids.extend(processed_features[other_id])

                ids_list.extend(higher_level_ids)

            # Check for duplicates and issue a warning
            id_counts = Counter(ids_list)  # Count occurrences of each ID
            unique_ids = sorted(set(ids_list))  # Deduplicate and sort
            duplicates = [id for id, count in id_counts.items() if count > 1] # Identify duplicates

            if duplicates:
                feedback.reportError(
                    f"Duplicate HP_IDs found and removed for HP_ID: {', '.join(duplicates)}, make sure this heatpump only connects to one pipe section"
                )
            
            if not unique_ids:
                geometry = pipe_feature.geometry()
                midpoint = geometry.interpolate(geometry.length() / 2).asPoint()
                raise QgsProcessingException(
                    f"A main pipe (Level {current_level}, {Trace_length:.1f} m long, "
                    f"midpoint at {midpoint.x():.1f}, {midpoint.y():.1f} in "
                    f"{pipes_layer_proj.crs().authid()}) has no heat pumps connected "
                    "to it or downstream of it -- a pipe carrying no flow can't be "
                    "dimensioned. This is usually a stretch of the main pipes layer "
                    "past the last connected building; trim it and re-run Main Pipe "
                    "Hierarchy and Pipe Topology or the full Build Pipe Network again."
                )

            combined_ids = ", ".join(unique_ids)

            # Update the current feature's combined_ids field
            feedback.pushInfo(f"Feature ID {pipe_feature.id()} updated combined IDs: {combined_ids}")

            
            #Step 3: Update field values
            new_feature["Section"] = "Pipe_branch_" + str(pipeNo)
            new_feature["SDR"] = 17
            new_feature["Trace_(m)"] = Trace_length
            new_feature["Number_of_traces"] = 1
            new_feature["Max_pressure_loss_(Pa)"] = 180 * Trace_length
            new_feature["HP_ID_vector"] = combined_ids
            out_features.append(new_feature)

            # Store the processed feature's HP_IDs in the dictionary
            current_id = pipe_feature.id()
            processed_features[current_id] = unique_ids

            # Update dat file
            dat_lines.append(
                f"{new_feature['Section']}\t{new_feature['SDR']}\t"
                f"{float(new_feature['Trace_(m)']):.2f}\t"  # Explicitly format to 2 decimal places
                f"{new_feature['Number_of_traces']}\t"
                f"{int(round(new_feature['Max_pressure_loss_(Pa)']))}\t"  # Ensure integer for MaxPLossPa
                f"{new_feature['HP_ID_vector']}\n"
            )
           
        
        # Write both outputs now that every check has passed (loading the
        # layer onto the map happens afterwards, in postProcessAlgorithm)
        feedback.pushInfo("") # Empty line for visibility of output
        feedback.pushInfo("Writing output files ...")
        try:
            output_handling.write_geojson(output_path, fields, QgsWkbTypes.LineString, crs, out_features)
        except OSError as exc:
            raise QgsProcessingException(str(exc)) from exc

        with open(dat_output_path, "w", encoding="utf-8") as dat_file:
            dat_file.writelines(dat_lines)

        feedback.pushInfo("Processing completed successfully.")
        
    def _crop_pipes(
        self, parameters, context, feedback, pipes_layer, service_pipes_layer, distance_area, cropped_mains_path=None
    ):
        """Crop the main pipes (see `_crop_network`), log what changed, return a cropped copy.

        With `cropped_mains_path`, the cropped pipes (with `ellip_length`
        re-measured) are also written there.
        """
        source_layer = self.parameterAsVectorLayer(parameters, self.SOURCE_LAYER, context)
        node = get_connection_node_geometry(source_layer)
        if node is None:
            raise QgsProcessingException(
                f"The source layer '{source_layer.name()}' has no connection node (a feature "
                "with 'is_connection_node' set) -- select the Source Placement output."
            )
        if source_layer.crs() != pipes_layer.crs():
            node.transform(QgsCoordinateTransform(source_layer.crs(), pipes_layer.crs(), context.transformContext()))

        has_level = "Level" in pipes_layer.fields().names()
        pipes = [
            (feature.id(), feature.geometry(), feature["Level"] if has_level else None)
            for feature in pipes_layer.getFeatures()
        ]
        services = [feature.geometry() for feature in service_pipes_layer.getFeatures()]

        feedback.pushInfo("Removing main pipes without heat pumps ...")
        kept, report = _crop_network(pipes, services, node.asPoint(), distance_area)
        for _, _, text in report:
            feedback.pushInfo(text)
        removed = [length for action, length, _ in report if action.startswith("Removed")]
        trimmed = [length for action, length, _ in report if action.startswith("Trimmed")]
        feedback.pushInfo(
            f"Removed {len(removed)} main pipe(s) ({sum(removed):.1f} m) and trimmed "
            f"{len(trimmed)} pipe end(s) ({sum(trimmed):.1f} m in total)."
        )
        if not kept:
            raise QgsProcessingException(
                "No service pipe connects to any main pipe, so no main pipe is left after "
                "removing the ones without heat pumps. Check that the service pipes touch "
                "the main pipes (within 0.1 m)."
            )

        cropped = QgsVectorLayer(
            f"{QgsWkbTypes.displayString(pipes_layer.wkbType())}?crs={pipes_layer.crs().authid()}",
            "cropped main pipes",
            "memory",
        )
        cropped.dataProvider().addAttributes(pipes_layer.fields())
        cropped.updateFields()
        features = []
        for feature in pipes_layer.getFeatures():
            if feature.id() not in kept:
                continue
            geometry = QgsGeometry(kept[feature.id()])
            if QgsWkbTypes.isMultiType(pipes_layer.wkbType()):
                geometry.convertToMultiType()
            new_feature = QgsFeature(cropped.fields())
            new_feature.setGeometry(geometry)
            new_feature.setAttributes(feature.attributes())
            features.append(new_feature)
        cropped.dataProvider().addFeatures(features)

        if cropped_mains_path:
            length_index = cropped.fields().indexOf("ellip_length")
            if length_index >= 0:
                for feature in features:
                    feature[length_index] = round(distance_area.measureLength(feature.geometry()), 1)
            try:
                output_handling.write_geojson(
                    cropped_mains_path, cropped.fields(), cropped.wkbType(), cropped.crs(), features
                )
            except OSError as exc:
                raise QgsProcessingException(str(exc)) from exc
            feedback.pushInfo("Cropped main pipes written for the main pipe hierarchy file.")
        return cropped

    def find_features_within_distance(self, input_feature, reference_layer, distance):
        """
        Find all features in the reference layer that are within a given distance
        of the input feature.
        """
        nearby_features = []
        input_geometry = input_feature.geometry()
        buffer_geometry = input_geometry.buffer(distance, segments=5)  # Create a buffer around the feature
    
        for reference_feature in reference_layer.getFeatures():
            if buffer_geometry.intersects(reference_feature.geometry()):
                nearby_features.append(reference_feature)
        return nearby_features

    def name(self):
        return "pipe_topology"

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr("Pipe Topology")

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '4. Pipe network steps'


    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def icon(self):
        return QIcon(utils.get_logo('logo6-pipes-alt.png'))

    def shortHelpString(self):
        return (
            "<p> This tool creates a pipe topology file for the thermonet that "
            "can be used as input to pythermonet.<p> "
            "<p> The tool requires two input files: <p> "
            "<p> 1. A pipe layer containing the"
            " main pipes of the thermonet with field 'Level' determining the"
            " hierarchy of the pipe network where 0=the highest level and 1,2,3,..."
            " are succesively lower levels. The Level determines which heatpump"
            "ID's are connected to which pipe segment<p> "
            "<p> 2. A service pipes layer containing the service "
            "pipes connecting each building/heatpump to the thermonet. "
            "This layer should hold the ID's of the heatpumps in a field called 'id_lokalId'. <p> "                
            " The tool stores the relevant information in new geojson and dat files. <p>"
            "<p> The output dat-file can be used as input for full "
            "dimensioning of the thermonet using pythermonet <p>"
        )

    def createInstance(self):
        return PipeTopologyAlgorithm()
